// words.js
const ALL_DATA = [
    { "id": 101, "en": "accept", "ja": "受け入れる", "cat": "動詞" },
    { "id": 102, "en": "achieve", "ja": "達成する", "cat": "動詞" },
    { "id": 103, "en": "act", "ja": "行動する", "cat": "動詞" },
    { "id": 104, "en": "add", "ja": "加える", "cat": "動詞" },
    { "id": 105, "en": "admit", "ja": "認める", "cat": "動詞" },
    { "id": 106, "en": "advise", "ja": "助言する", "cat": "動詞" },
    { "id": 107, "en": "afford", "ja": "～する余裕がある", "cat": "動詞" },
    { "id": 108, "en": "agree", "ja": "同意する", "cat": "動詞" },
    { "id": 109, "en": "allow", "ja": "許す", "cat": "動詞" },
    { "id": 110, "en": "appear", "ja": "現れる", "cat": "動詞" },
    { "id": 111, "en": "apply", "ja": "申し込む", "cat": "動詞" },
    { "id": 112, "en": "argue", "ja": "議論する", "cat": "動詞" },
    { "id": 113, "en": "arrange", "ja": "手配する", "cat": "動詞" },
    { "id": 114, "en": "arrive", "ja": "到着する", "cat": "動詞" },
    { "id": 115, "en": "attend", "ja": "出席する", "cat": "動詞" },
    { "id": 116, "en": "avoid", "ja": "避ける", "cat": "動詞" },
    { "id": 117, "en": "bake", "ja": "（パン等を）焼く", "cat": "動詞" },
    { "id": 118, "en": "become", "ja": "…になる", "cat": "動詞" },
    { "id": 119, "en": "believe", "ja": "信じる", "cat": "動詞" },
    { "id": 120, "en": "belong", "ja": "所属する", "cat": "動詞" },
    { "id": 121, "en": "boil", "ja": "ゆでる", "cat": "動詞" },
    { "id": 122, "en": "borrow", "ja": "借りる", "cat": "動詞" },
    { "id": 123, "en": "break", "ja": "壊す", "cat": "動詞" },
    { "id": 124, "en": "brush", "ja": "磨く", "cat": "動詞" },
    { "id": 125, "en": "build", "ja": "建てる", "cat": "動詞" },
    { "id": 126, "en": "burn", "ja": "燃やす", "cat": "動詞" },
    { "id": 127, "en": "buy", "ja": "買う", "cat": "動詞" },
    { "id": 128, "en": "calculate", "ja": "計算する", "cat": "動詞" },
    { "id": 129, "en": "care", "ja": "気にかける", "cat": "動詞" },
    { "id": 130, "en": "carry", "ja": "運ぶ", "cat": "動詞" },
    { "id": 131, "en": "catch", "ja": "捕まえる", "cat": "動詞" },
    { "id": 132, "en": "cause", "ja": "引き起こす", "cat": "動詞" },
    { "id": 133, "en": "celebrate", "ja": "祝う", "cat": "動詞" },
    { "id": 134, "en": "change", "ja": "変える", "cat": "動詞" },
    { "id": 135, "en": "check", "ja": "確認する", "cat": "動詞" },
    { "id": 136, "en": "cheer", "ja": "応援する", "cat": "動詞" },
    { "id": 137, "en": "choose", "ja": "選ぶ", "cat": "動詞" },
    { "id": 138, "en": "clean", "ja": "掃除する", "cat": "動詞" },
    { "id": 139, "en": "climb", "ja": "登る", "cat": "動詞" },
    { "id": 140, "en": "collect", "ja": "集める", "cat": "動詞" },
    { "id": 141, "en": "communicate", "ja": "意思疎通する", "cat": "動詞" },
    { "id": 142, "en": "compare", "ja": "比較する", "cat": "動詞" },
    { "id": 143, "en": "complain", "ja": "不平を言う", "cat": "動詞" },
    { "id": 144, "en": "complete", "ja": "完了する", "cat": "動詞" },
    { "id": 145, "en": "concentrate", "ja": "集中する", "cat": "動詞" },
    { "id": 146, "en": "consider", "ja": "よく考える", "cat": "動詞" },
    { "id": 147, "en": "continue", "ja": "続ける", "cat": "動詞" },
    { "id": 148, "en": "control", "ja": "管理する", "cat": "動詞" },
    { "id": 149, "en": "cook", "ja": "料理する", "cat": "動詞" },
    { "id": 150, "en": "copy", "ja": "写す", "cat": "動詞" },
    { "id": 151, "en": "cost", "ja": "費用がかかる", "cat": "動詞" },
    { "id": 152, "en": "cover", "ja": "覆う", "cat": "動詞" },
    { "id": 153, "en": "create", "ja": "創造する", "cat": "動詞" },
    { "id": 154, "en": "cross", "ja": "横切る", "cat": "動詞" },
    { "id": 155, "en": "cry", "ja": "泣く", "cat": "動詞" },
    { "id": 156, "en": "cut", "ja": "切る", "cat": "動詞" },
    { "id": 157, "en": "dance", "ja": "踊る", "cat": "動詞" },
    { "id": 158, "en": "decide", "ja": "決める", "cat": "動詞" },
    { "id": 159, "en": "depend", "ja": "依存する", "cat": "動詞" },
    { "id": 160, "en": "describe", "ja": "描写する", "cat": "動詞" },
    { "id": 161, "en": "design", "ja": "設計する", "cat": "動詞" },
    { "id": 162, "en": "destroy", "ja": "破壊する", "cat": "動詞" },
    { "id": 163, "en": "develop", "ja": "発展させる", "cat": "動詞" },
    { "id": 164, "en": "die", "ja": "死ぬ", "cat": "動詞" },
    { "id": 165, "en": "discover", "ja": "発見する", "cat": "動詞" },
    { "id": 166, "en": "discuss", "ja": "議論する", "cat": "動詞" },
    { "id": 167, "en": "divide", "ja": "分ける", "cat": "動詞" },
    { "id": 168, "en": "draw", "ja": "描く", "cat": "動詞" },
    { "id": 169, "en": "dream", "ja": "夢を見る", "cat": "動詞" },
    { "id": 170, "en": "drink", "ja": "飲む", "cat": "動詞" },
    { "id": 171, "en": "drive", "ja": "運転する", "cat": "動詞" },
    { "id": 172, "en": "drop", "ja": "落とす", "cat": "動詞" },
    { "id": 173, "en": "earn", "ja": "稼ぐ", "cat": "動詞" },
    { "id": 174, "en": "eat", "ja": "食べる", "cat": "動詞" },
    { "id": 175, "en": "encourage", "ja": "励ます", "cat": "動詞" },
    { "id": 176, "en": "enjoy", "ja": "楽しむ", "cat": "動詞" },
    { "id": 177, "en": "enter", "ja": "入る", "cat": "動詞" },
    { "id": 178, "en": "exchange", "ja": "交換する", "cat": "動詞" },
    { "id": 179, "en": "excite", "ja": "興奮させる", "cat": "動詞" },
    { "id": 180, "en": "expect", "ja": "期待する", "cat": "動詞" },
    { "id": 181, "en": "explain", "ja": "説明する", "cat": "動詞" },
    { "id": 182, "en": "express", "ja": "表現する", "cat": "動詞" },
    { "id": 183, "en": "fail", "ja": "失敗する", "cat": "動詞" },
    { "id": 184, "en": "fall", "ja": "落ちる", "cat": "動詞" },
    { "id": 185, "en": "feed", "ja": "エサをやる", "cat": "動詞" },
    { "id": 186, "en": "feel", "ja": "感じる", "cat": "動詞" },
    { "id": 187, "en": "fight", "ja": "戦う", "cat": "動詞" },
    { "id": 188, "en": "fill", "ja": "満たす", "cat": "動詞" },
    { "id": 189, "en": "find", "ja": "見つける", "cat": "動詞" },
    { "id": 190, "en": "finish", "ja": "終える", "cat": "動詞" },
    { "id": 191, "en": "fix", "ja": "修理する", "cat": "動詞" },
    { "id": 192, "en": "fly", "ja": "飛ぶ", "cat": "動詞" },
    { "id": 193, "en": "follow", "ja": "従う", "cat": "動詞" },
    { "id": 194, "en": "forget", "ja": "忘れる", "cat": "動詞" },
    { "id": 195, "en": "forgive", "ja": "許す", "cat": "動詞" },
    { "id": 196, "en": "gather", "ja": "集める", "cat": "動詞" },
    { "id": 197, "en": "get", "ja": "手に入れる", "cat": "動詞" },
    { "id": 198, "en": "give", "ja": "与える", "cat": "動詞" },
    { "id": 199, "en": "go", "ja": "行く", "cat": "動詞" },
    { "id": 200, "en": "grow", "ja": "成長する", "cat": "動詞" },
    { "id": 201, "en": "guess", "ja": "推測する", "cat": "動詞" },
    { "id": 202, "en": "guide", "ja": "案内する", "cat": "動詞" },
    { "id": 203, "en": "happen", "ja": "起こる", "cat": "動詞" },
    { "id": 204, "en": "hate", "ja": "憎む", "cat": "動詞" },
    { "id": 205, "en": "have", "ja": "持っている", "cat": "動詞" },
    { "id": 206, "en": "hear", "ja": "聞こえる", "cat": "動詞" },
    { "id": 207, "en": "help", "ja": "助ける", "cat": "動詞" },
    { "id": 208, "en": "hide", "ja": "隠す", "cat": "動詞" },
    { "id": 209, "en": "hit", "ja": "打つ", "cat": "動詞" },
    { "id": 210, "en": "hold", "ja": "開催する", "cat": "動詞" },
    { "id": 211, "en": "hope", "ja": "望む", "cat": "動詞" },
    { "id": 212, "en": "hunt", "ja": "狩る", "cat": "動詞" },
    { "id": 213, "en": "hurt", "ja": "傷つける", "cat": "動詞" },
    { "id": 214, "en": "imagine", "ja": "想像する", "cat": "動詞" },
    { "id": 215, "en": "improve", "ja": "向上させる", "cat": "動詞" },
    { "id": 216, "en": "include", "ja": "含む", "cat": "動詞" },
    { "id": 217, "en": "increase", "ja": "増える", "cat": "動詞" },
    { "id": 218, "en": "inform", "ja": "知らせる", "cat": "動詞" },
    { "id": 219, "en": "introduce", "ja": "紹介する", "cat": "動詞" },
    { "id": 220, "en": "invent", "ja": "発明する", "cat": "動詞" },
    { "id": 221, "en": "invite", "ja": "招待する", "cat": "動詞" },
    { "id": 222, "en": "join", "ja": "参加する", "cat": "動詞" },
    { "id": 223, "en": "jump", "ja": "跳ぶ", "cat": "動詞" },
    { "id": 224, "en": "keep", "ja": "保つ", "cat": "動詞" },
    { "id": 225, "en": "kick", "ja": "蹴る", "cat": "動詞" },
    { "id": 226, "en": "kill", "ja": "殺す", "cat": "動詞" },
    { "id": 227, "en": "knock", "ja": "ノックする", "cat": "動詞" },
    { "id": 228, "en": "know", "ja": "知っている", "cat": "動詞" },
    { "id": 229, "en": "laugh", "ja": "笑う", "cat": "動詞" },
    { "id": 230, "en": "lead", "ja": "導く", "cat": "動詞" },
    { "id": 231, "en": "learn", "ja": "学ぶ", "cat": "動詞" },
    { "id": 232, "en": "leave", "ja": "去る・残す", "cat": "動詞" },
    { "id": 233, "en": "lend", "ja": "貸す", "cat": "動詞" },
    { "id": 234, "en": "let", "ja": "～させる", "cat": "動詞" },
    { "id": 235, "en": "lie", "ja": "横たわる", "cat": "動詞" },
    { "id": 236, "en": "like", "ja": "好む", "cat": "動詞" },
    { "id": 237, "en": "listen", "ja": "聞く", "cat": "動詞" },
    { "id": 238, "en": "live", "ja": "住む", "cat": "動詞" },
    { "id": 239, "en": "look", "ja": "見る", "cat": "動詞" },
    { "id": 240, "en": "lose", "ja": "失う", "cat": "動詞" },
    { "id": 241, "en": "love", "ja": "愛する", "cat": "動詞" },
    { "id": 242, "en": "make", "ja": "作る", "cat": "動詞" },
    { "id": 243, "en": "manage", "ja": "何とかする", "cat": "動詞" },
    { "id": 244, "en": "marry", "ja": "結婚する", "cat": "動詞" },
    { "id": 245, "en": "mean", "ja": "意味する", "cat": "動詞" },
    { "id": 246, "en": "meet", "ja": "会う", "cat": "動詞" },
    { "id": 247, "en": "miss", "ja": "逃す・寂しい", "cat": "動詞" },
    { "id": 248, "en": "move", "ja": "動く", "cat": "動詞" },
    { "id": 249, "en": "need", "ja": "必要とする", "cat": "動詞" },
    { "id": 250, "en": "notice", "ja": "気づく", "cat": "動詞" },
    { "id": 251, "en": "offer", "ja": "申し出る", "cat": "動詞" },
    { "id": 252, "en": "open", "ja": "開ける", "cat": "動詞" },
    { "id": 253, "en": "order", "ja": "注文する", "cat": "動詞" },
    { "id": 254, "en": "paint", "ja": "描く・塗る", "cat": "動詞" },
    { "id": 255, "en": "pass", "ja": "手渡す・合格する", "cat": "動詞" },
    { "id": 256, "en": "pay", "ja": "支払う", "cat": "動詞" },
    { "id": 257, "en": "perform", "ja": "演じる", "cat": "動詞" },
    { "id": 258, "en": "pick", "ja": "選ぶ・摘む", "cat": "動詞" },
    { "id": 259, "en": "plan", "ja": "計画する", "cat": "動詞" },
    { "id": 260, "en": "plant", "ja": "植える", "cat": "動詞" },
    { "id": 261, "en": "play", "ja": "遊ぶ・演奏する", "cat": "動詞" },
    { "id": 262, "en": "point", "ja": "指差す", "cat": "動詞" },
    { "id": 263, "en": "practice", "ja": "練習する", "cat": "動詞" },
    { "id": 264, "en": "prefer", "ja": "～を好む", "cat": "動詞" },
    { "id": 265, "en": "prepare", "ja": "準備する", "cat": "動詞" },
    { "id": 266, "en": "present", "ja": "贈る", "cat": "動詞" },
    { "id": 267, "en": "press", "ja": "押す", "cat": "動詞" },
    { "id": 268, "en": "prevent", "ja": "防ぐ", "cat": "動詞" },
    { "id": 269, "en": "produce", "ja": "生産する", "cat": "動詞" },
    { "id": 270, "en": "promise", "ja": "約束する", "cat": "動詞" },
    { "id": 271, "en": "protect", "ja": "保護する", "cat": "動詞" },
    { "id": 272, "en": "prove", "ja": "証明する", "cat": "動詞" },
    { "id": 273, "en": "provide", "ja": "提供する", "cat": "動詞" },
    { "id": 274, "en": "pull", "ja": "引く", "cat": "動詞" },
    { "id": 275, "en": "push", "ja": "押す", "cat": "動詞" },
    { "id": 276, "en": "put", "ja": "置く", "cat": "動詞" },
    { "id": 277, "en": "quit", "ja": "やめる", "cat": "動詞" },
    { "id": 278, "en": "raise", "ja": "上げる・育てる", "cat": "動詞" },
    { "id": 279, "en": "reach", "ja": "到着する", "cat": "動詞" },
    { "id": 280, "en": "read", "ja": "読む", "cat": "動詞" },
    { "id": 281, "en": "realize", "ja": "悟る・実現する", "cat": "動詞" },
    { "id": 282, "en": "receive", "ja": "受け取る", "cat": "動詞" },
    { "id": 283, "en": "recognize", "ja": "認識する", "cat": "動詞" },
    { "id": 284, "en": "recommend", "ja": "勧める", "cat": "動詞" },
    { "id": 285, "en": "record", "ja": "記録する", "cat": "動詞" },
    { "id": 286, "en": "recover", "ja": "回復する", "cat": "動詞" },
    { "id": 287, "en": "reduce", "ja": "減らす", "cat": "動詞" },
    { "id": 288, "en": "refuse", "ja": "断る", "cat": "動詞" },
    { "id": 289, "en": "remain", "ja": "ままである", "cat": "動詞" },
    { "id": 290, "en": "remember", "ja": "覚えている", "cat": "動詞" },
    { "id": 291, "en": "remind", "ja": "思い出させる", "cat": "動詞" },
    { "id": 292, "en": "remove", "ja": "取り除く", "cat": "動詞" },
    { "id": 293, "en": "repair", "ja": "修理する", "cat": "動詞" },
    { "id": 294, "en": "repeat", "ja": "繰り返す", "cat": "動詞" },
    { "id": 295, "en": "reply", "ja": "返事をする", "cat": "動詞" },
    { "id": 296, "en": "report", "ja": "報告する", "cat": "動詞" },
    { "id": 297, "en": "request", "ja": "頼む", "cat": "動詞" },
    { "id": 298, "en": "require", "ja": "必要とする", "cat": "動詞" },
    { "id": 299, "en": "respect", "ja": "尊敬する", "cat": "動詞" },
    { "id": 300, "en": "rest", "ja": "休む", "cat": "動詞" },
    { "id": 301, "en": "return", "ja": "戻る", "cat": "動詞" },
    { "id": 302, "en": "ride", "ja": "乗る", "cat": "動詞" },
    { "id": 303, "en": "rise", "ja": "昇る", "cat": "動詞" },
    { "id": 304, "en": "run", "ja": "走る", "cat": "動詞" },
    { "id": 305, "en": "save", "ja": "救う・節約する", "cat": "動詞" },
    { "id": 306, "en": "say", "ja": "言う", "cat": "動詞" },
    { "id": 307, "en": "search", "ja": "探す", "cat": "動詞" },
    { "id": 308, "en": "see", "ja": "見る", "cat": "動詞" },
    { "id": 309, "en": "sell", "ja": "売る", "cat": "動詞" },
    { "id": 310, "en": "send", "ja": "送る", "cat": "動詞" },
    { "id": 311, "en": "serve", "ja": "食事を出す", "cat": "動詞" },
    { "id": 312, "en": "set", "ja": "置く・設定する", "cat": "動詞" },
    { "id": 313, "en": "shake", "ja": "振る", "cat": "動詞" },
    { "id": 314, "en": "share", "ja": "共有する", "cat": "動詞" },
    { "id": 315, "en": "shoot", "ja": "撃つ・撮影する", "cat": "動詞" },
    { "id": 316, "en": "show", "ja": "見せる", "cat": "動詞" },
    { "id": 317, "en": "shut", "ja": "閉める", "cat": "動詞" },
    { "id": 318, "en": "sing", "ja": "歌う", "cat": "動詞" },
    { "id": 319, "en": "sit", "ja": "座る", "cat": "動詞" },
    { "id": 320, "en": "sleep", "ja": "眠る", "cat": "動詞" },
    { "id": 321, "en": "smile", "ja": "微笑む", "cat": "動詞" },
    { "id": 322, "en": "solve", "ja": "解決する", "cat": "動詞" },
    { "id": 323, "en": "sound", "ja": "～に聞こえる", "cat": "動詞" },
    { "id": 324, "en": "speak", "ja": "話す", "cat": "動詞" },
    { "id": 325, "en": "spend", "ja": "過ごす・費やす", "cat": "動詞" },
    { "id": 326, "en": "spread", "ja": "広がる", "cat": "動詞" },
    { "id": 327, "en": "stand", "ja": "立つ", "cat": "動詞" },
    { "id": 328, "en": "start", "ja": "始める", "cat": "動詞" },
    { "id": 329, "en": "stay", "ja": "滞在する", "cat": "動詞" },
    { "id": 330, "en": "steal", "ja": "盗む", "cat": "動詞" },
    { "id": 331, "en": "stop", "ja": "止まる", "cat": "動詞" },
    { "id": 332, "en": "study", "ja": "勉強する", "cat": "動詞" },
    { "id": 333, "en": "succeed", "ja": "成功する", "cat": "動詞" },
    { "id": 334, "en": "suggest", "ja": "提案する", "cat": "動詞" },
    { "id": 335, "en": "support", "ja": "支持する", "cat": "動詞" },
    { "id": 336, "en": "surprise", "ja": "驚かせる", "cat": "動詞" },
    { "id": 337, "en": "survive", "ja": "生き残る", "cat": "動詞" },
    { "id": 338, "en": "swim", "ja": "泳ぐ", "cat": "動詞" },
    { "id": 339, "en": "take", "ja": "取る・連れて行く", "cat": "動詞" },
    { "id": 340, "en": "talk", "ja": "話す", "cat": "動詞" },
    { "id": 341, "en": "teach", "ja": "教える", "cat": "動詞" },
    { "id": 342, "en": "tell", "ja": "伝える", "cat": "動詞" },
    { "id": 343, "en": "think", "ja": "思う・考える", "cat": "動詞" },
    { "id": 344, "en": "throw", "ja": "投げる", "cat": "動詞" },
    { "id": 345, "en": "touch", "ja": "触れる", "cat": "動詞" },
    { "id": 346, "en": "travel", "ja": "旅行する", "cat": "動詞" },
    { "id": 347, "en": "try", "ja": "試す・努力する", "cat": "動詞" },
    { "id": 348, "en": "turn", "ja": "曲がる・回す", "cat": "動詞" },
    { "id": 349, "en": "understand", "ja": "理解する", "cat": "動詞" },
    { "id": 350, "en": "use", "ja": "使う", "cat": "動詞" },
    { "id": 351, "en": "visit", "ja": "訪れる", "cat": "動詞" },
    { "id": 352, "en": "wait", "ja": "待つ", "cat": "動詞" },
    { "id": 353, "en": "wake", "ja": "目が覚める", "cat": "動詞" },
    { "id": 354, "en": "walk", "ja": "歩く", "cat": "動詞" },
    { "id": 355, "en": "want", "ja": "欲しい", "cat": "動詞" },
    { "id": 356, "en": "wash", "ja": "洗う", "cat": "動詞" },
    { "id": 357, "en": "watch", "ja": "見る", "cat": "動詞" },
    { "id": 358, "en": "wear", "ja": "着ている", "cat": "動詞" },
    { "id": 359, "en": "win", "ja": "勝つ", "cat": "動詞" },
    { "id": 360, "en": "wish", "ja": "願う", "cat": "動詞" },
    { "id": 361, "en": "wonder", "ja": "不思議に思う", "cat": "動詞" },
    { "id": 362, "en": "work", "ja": "働く", "cat": "動詞" },
    { "id": 363, "en": "worry", "ja": "心配する", "cat": "動詞" },
    { "id": 364, "en": "write", "ja": "書く", "cat": "動詞" },
    { "id": 401, "en": "accident", "ja": "事故", "cat": "名詞" },
    { "id": 402, "en": "activity", "ja": "活動", "cat": "名詞" },
    { "id": 403, "en": "actor", "ja": "俳優", "cat": "名詞" },
    { "id": 404, "en": "address", "ja": "住所", "cat": "名詞" },
    { "id": 405, "en": "adult", "ja": "大人", "cat": "名詞" },
    { "id": 406, "en": "advantage", "ja": "利点", "cat": "名詞" },
    { "id": 407, "en": "adventure", "ja": "冒険", "cat": "名詞" },
    { "id": 408, "en": "advice", "ja": "助言", "cat": "名詞" },
    { "id": 409, "en": "age", "ja": "年齢・時代", "cat": "名詞" },
    { "id": 410, "en": "agent", "ja": "代理人", "cat": "名詞" },
    { "id": 411, "en": "amount", "ja": "量", "cat": "名詞" },
    { "id": 412, "en": "angel", "ja": "天使", "cat": "名詞" },
    { "id": 413, "en": "animal", "ja": "動物", "cat": "名詞" },
    { "id": 414, "en": "answer", "ja": "答え", "cat": "名詞" },
    { "id": 415, "en": "area", "ja": "地域", "cat": "名詞" },
    { "id": 416, "en": "arm", "ja": "腕", "cat": "名詞" },
    { "id": 417, "en": "army", "ja": "軍隊", "cat": "名詞" },
    { "id": 418, "en": "art", "ja": "芸術", "cat": "名詞" },
    { "id": 419, "en": "article", "ja": "記事", "cat": "名詞" },
    { "id": 420, "en": "artist", "ja": "芸術家", "cat": "名詞" },
    { "id": 421, "en": "attention", "ja": "注意", "cat": "名詞" },
    { "id": 422, "en": "aunt", "ja": "おば", "cat": "名詞" },
    { "id": 423, "en": "author", "ja": "著者", "cat": "名詞" },
    { "id": 424, "en": "autumn", "ja": "秋", "cat": "名詞" },
    { "id": 425, "en": "average", "ja": "平均", "cat": "名詞" },
    { "id": 426, "en": "award", "ja": "賞", "cat": "名詞" },
    { "id": 427, "en": "baby", "ja": "赤ちゃん", "cat": "名詞" },
    { "id": 428, "en": "back", "ja": "背中・後ろ", "cat": "名詞" },
    { "id": 429, "en": "background", "ja": "背景", "cat": "名詞" },
    { "id": 430, "en": "bag", "ja": "かばん", "cat": "名詞" },
    { "id": 431, "en": "ball", "ja": "ボール", "cat": "名詞" },
    { "id": 432, "en": "balloon", "ja": "風船", "cat": "名詞" },
    { "id": 433, "en": "band", "ja": "バンド", "cat": "名詞" },
    { "id": 434, "en": "bank", "ja": "銀行・土手", "cat": "名詞" },
    { "id": 435, "en": "base", "ja": "土台・基地", "cat": "名詞" },
    { "id": 436, "en": "bath", "ja": "入浴", "cat": "名詞" },
    { "id": 437, "en": "beach", "ja": "浜辺", "cat": "名詞" },
    { "id": 438, "en": "bear", "ja": "クマ", "cat": "名詞" },
    { "id": 439, "en": "beginning", "ja": "始まり", "cat": "名詞" },
    { "id": 440, "en": "bell", "ja": "鈴・鐘", "cat": "名詞" },
    { "id": 441, "en": "bicycle", "ja": "自転車", "cat": "名詞" },
    { "id": 442, "en": "bill", "ja": "請求書・紙幣", "cat": "名詞" },
    { "id": 443, "en": "bird", "ja": "鳥", "cat": "名詞" },
    { "id": 444, "en": "birthday", "ja": "誕生日", "cat": "名詞" },
    { "id": 445, "en": "block", "ja": "区画・塊", "cat": "名詞" },
    { "id": 446, "en": "blood", "ja": "血", "cat": "名詞" },
    { "id": 447, "en": "board", "ja": "板・委員会", "cat": "名詞" },
    { "id": 448, "en": "boat", "ja": "ボート", "cat": "名詞" },
    { "id": 449, "en": "body", "ja": "体", "cat": "名詞" },
    { "id": 450, "en": "bone", "ja": "骨", "cat": "名詞" },
    { "id": 451, "en": "book", "ja": "本", "cat": "名詞" },
    { "id": 452, "en": "boss", "ja": "上司", "cat": "名詞" },
    { "id": 453, "en": "bottle", "ja": "瓶", "cat": "名詞" },
    { "id": 454, "en": "bottom", "ja": "底", "cat": "名詞" },
    { "id": 455, "en": "box", "ja": "箱", "cat": "名詞" },
    { "id": 456, "en": "brain", "ja": "脳", "cat": "名詞" },
    { "id": 457, "en": "branch", "ja": "枝・支店", "cat": "名詞" },
    { "id": 458, "en": "bread", "ja": "パン", "cat": "名詞" },
    { "id": 459, "en": "break", "ja": "休憩", "cat": "名詞" },
    { "id": 460, "en": "breakfast", "ja": "朝食", "cat": "名詞" },
    { "id": 461, "en": "bridge", "ja": "橋", "cat": "名詞" },
    { "id": 462, "en": "brother", "ja": "兄・弟", "cat": "名詞" },
    { "id": 463, "en": "building", "ja": "建物", "cat": "名詞" },
    { "id": 464, "en": "bus", "ja": "バス", "cat": "名詞" },
    { "id": 465, "en": "business", "ja": "仕事・事業", "cat": "名詞" },
    { "id": 466, "en": "calendar", "ja": "カレンダー", "cat": "名詞" },
    { "id": 467, "en": "camera", "ja": "カメラ", "cat": "名詞" },
    { "id": 468, "en": "camp", "ja": "キャンプ", "cat": "名詞" },
    { "id": 469, "en": "capital", "ja": "首都・資本", "cat": "名詞" },
    { "id": 470, "en": "captain", "ja": "主将", "cat": "名詞" },
    { "id": 471, "en": "car", "ja": "車", "cat": "名詞" },
    { "id": 472, "en": "card", "ja": "カード", "cat": "名詞" },
    { "id": 473, "en": "care", "ja": "世話・注意", "cat": "名詞" },
    { "id": 474, "en": "career", "ja": "経歴", "cat": "名詞" },
    { "id": 475, "en": "case", "ja": "場合・箱", "cat": "名詞" },
    { "id": 476, "en": "cash", "ja": "現金", "cat": "名詞" },
    { "id": 477, "en": "cat", "ja": "猫", "cat": "名詞" },
    { "id": 478, "en": "cause", "ja": "原因", "cat": "名詞" },
    { "id": 479, "en": "center", "ja": "中心", "cat": "名詞" },
    { "id": 480, "en": "century", "ja": "世紀", "cat": "名詞" },
    { "id": 481, "en": "ceremony", "ja": "式典", "cat": "名詞" },
    { "id": 482, "en": "chair", "ja": "椅子", "cat": "名詞" },
    { "id": 483, "en": "chance", "ja": "機会", "cat": "名詞" },
    { "id": 484, "en": "change", "ja": "変化・お釣り", "cat": "名詞" },
    { "id": 485, "en": "character", "ja": "性格・登場人物", "cat": "名詞" },
    { "id": 486, "en": "charge", "ja": "料金・責任", "cat": "名詞" },
    { "id": 487, "en": "check", "ja": "小切手・勘定", "cat": "名詞" },
    { "id": 488, "en": "chef", "ja": "料理人", "cat": "名詞" },
    { "id": 489, "en": "child", "ja": "子供", "cat": "名詞" },
    { "id": 490, "en": "choice", "ja": "選択", "cat": "名詞" },
    { "id": 491, "en": "church", "ja": "教会", "cat": "名詞" },
    { "id": 492, "en": "circle", "ja": "円", "cat": "名詞" },
    { "id": 493, "en": "city", "ja": "都市", "cat": "名詞" },
    { "id": 494, "en": "class", "ja": "授業・階級", "cat": "名詞" },
    { "id": 495, "en": "classmate", "ja": "同級生", "cat": "名詞" },
    { "id": 496, "en": "clerk", "ja": "店員・事務員", "cat": "名詞" },
    { "id": 497, "en": "climate", "ja": "気候", "cat": "名詞" },
    { "id": 498, "en": "clock", "ja": "時計", "cat": "名詞" },
    { "id": 499, "en": "cloth", "ja": "布", "cat": "名詞" },
    { "id": 500, "en": "clothes", "ja": "服", "cat": "名詞" },
    { "id": 501, "en": "cloud", "ja": "雲", "cat": "名詞" },
    { "id": 502, "en": "club", "ja": "クラブ", "cat": "名詞" },
    { "id": 503, "en": "coach", "ja": "コーチ", "cat": "名詞" },
    { "id": 504, "en": "coast", "ja": "海岸", "cat": "名詞" },
    { "id": 505, "en": "coat", "ja": "コート", "cat": "名詞" },
    { "id": 506, "en": "coffee", "ja": "コーヒー", "cat": "名詞" },
    { "id": 507, "en": "coin", "ja": "硬貨", "cat": "名詞" },
    { "id": 508, "en": "college", "ja": "大学", "cat": "名詞" },
    { "id": 509, "en": "color", "ja": "色", "cat": "名詞" },
    { "id": 510, "en": "company", "ja": "会社・仲間", "cat": "名詞" },
    { "id": 511, "en": "competition", "ja": "競争", "cat": "名詞" },
    { "id": 512, "en": "computer", "ja": "コンピュータ", "cat": "名詞" },
    { "id": 513, "en": "concert", "ja": "演奏会", "cat": "名詞" },
    { "id": 514, "en": "condition", "ja": "状態・条件", "cat": "名詞" },
    { "id": 515, "en": "contest", "ja": "競技会", "cat": "名詞" },
    { "id": 516, "en": "continent", "ja": "大陸", "cat": "名詞" },
    { "id": 517, "en": "conversation", "ja": "会話", "cat": "名詞" },
    { "id": 518, "en": "cook", "ja": "料理人", "cat": "名詞" },
    { "id": 519, "en": "cookie", "ja": "クッキー", "cat": "名詞" },
    { "id": 520, "en": "corner", "ja": "角", "cat": "名詞" },
    { "id": 521, "en": "cost", "ja": "費用", "cat": "名詞" },
    { "id": 522, "en": "country", "ja": "国・田舎", "cat": "名詞" },
    { "id": 523, "en": "countryside", "ja": "田舎", "cat": "名詞" },
    { "id": 524, "en": "course", "ja": "進路・講座", "cat": "名詞" },
    { "id": 525, "en": "cousin", "ja": "いとこ", "cat": "名詞" },
    { "id": 526, "en": "cover", "ja": "表紙・カバー", "cat": "名詞" },
    { "id": 527, "en": "cow", "ja": "牛", "cat": "名詞" },
    { "id": 528, "en": "cream", "ja": "クリーム", "cat": "名詞" },
    { "id": 529, "en": "crowd", "ja": "群衆", "cat": "名詞" },
    { "id": 530, "en": "culture", "ja": "文化", "cat": "名詞" },
    { "id": 531, "en": "cup", "ja": "カップ", "cat": "名詞" },
    { "id": 532, "en": "curtain", "ja": "カーテン", "cat": "名詞" },
    { "id": 533, "en": "custom", "ja": "習慣", "cat": "名詞" },
    { "id": 534, "en": "customer", "ja": "客", "cat": "名詞" },
    { "id": 535, "en": "damage", "ja": "損害", "cat": "名詞" },
    { "id": 536, "en": "danger", "ja": "危険", "cat": "名詞" },
    { "id": 537, "en": "daughter", "ja": "娘", "cat": "名詞" },
    { "id": 538, "en": "day", "ja": "日・昼間", "cat": "名詞" },
    { "id": 539, "en": "death", "ja": "死", "cat": "名詞" },
    { "id": 540, "en": "decision", "ja": "決定", "cat": "名詞" },
    { "id": 541, "en": "degree", "ja": "程度・度", "cat": "名詞" },
    { "id": 542, "en": "dentist", "ja": "歯医者", "cat": "名詞" },
    { "id": 543, "en": "department", "ja": "部門・売り場", "cat": "名詞" },
    { "id": 544, "en": "design", "ja": "設計", "cat": "名詞" },
    { "id": 545, "en": "desk", "ja": "机", "cat": "名詞" },
    { "id": 546, "en": "diary", "ja": "日記", "cat": "名詞" },
    { "id": 547, "en": "dictionary", "ja": "辞書", "cat": "名詞" },
    { "id": 548, "en": "difference", "ja": "違い", "cat": "名詞" },
    { "id": 549, "en": "dinner", "ja": "夕食", "cat": "名詞" },
    { "id": 550, "en": "direction", "ja": "方向・指示", "cat": "名詞" },
    { "id": 551, "en": "director", "ja": "監督・重役", "cat": "名詞" },
    { "id": 552, "en": "discount", "ja": "割引", "cat": "名詞" },
    { "id": 553, "en": "dish", "ja": "皿・料理", "cat": "名詞" },
    { "id": 554, "en": "doctor", "ja": "医者・博士", "cat": "名詞" },
    { "id": 555, "en": "dog", "ja": "犬", "cat": "名詞" },
    { "id": 556, "en": "doll", "ja": "人形", "cat": "名詞" },
    { "id": 557, "en": "dollar", "ja": "ドル", "cat": "名詞" },
    { "id": 558, "en": "door", "ja": "ドア", "cat": "名詞" },
    { "id": 559, "en": "dream", "ja": "夢", "cat": "名詞" },
    { "id": 560, "en": "dress", "ja": "ドレス・服", "cat": "名詞" },
    { "id": 561, "en": "drink", "ja": "飲み物", "cat": "名詞" },
    { "id": 562, "en": "driver", "ja": "運転手", "cat": "名詞" },
    { "id": 563, "en": "drug", "ja": "薬", "cat": "名詞" },
    { "id": 564, "en": "ear", "ja": "耳", "cat": "名詞" },
    { "id": 565, "en": "earth", "ja": "地球・土", "cat": "名詞" },
    { "id": 566, "en": "earthquake", "ja": "地震", "cat": "名詞" },
    { "id": 567, "en": "east", "ja": "東", "cat": "名詞" },
    { "id": 568, "en": "education", "ja": "教育", "cat": "名詞" },
    { "id": 569, "en": "effect", "ja": "効果・影響", "cat": "名詞" },
    { "id": 570, "en": "effort", "ja": "努力", "cat": "名詞" },
    { "id": 571, "en": "egg", "ja": "卵", "cat": "名詞" },
    { "id": 572, "en": "elevator", "ja": "エレベーター", "cat": "名詞" },
    { "id": 573, "en": "email", "ja": "Eメール", "cat": "名詞" },
    { "id": 574, "en": "end", "ja": "終わり・端", "cat": "名詞" },
    { "id": 575, "en": "energy", "ja": "エネルギー", "cat": "名詞" },
    { "id": 576, "en": "engine", "ja": "エンジン", "cat": "名詞" },
    { "id": 577, "en": "engineer", "ja": "技師", "cat": "名詞" },
    { "id": 578, "en": "entrance", "ja": "入り口", "cat": "名詞" },
    { "id": 579, "en": "environment", "ja": "環境", "cat": "名詞" },
    { "id": 580, "en": "eraser", "ja": "消しゴム", "cat": "名詞" },
    { "id": 581, "en": "error", "ja": "誤り", "cat": "名詞" },
    { "id": 582, "en": "event", "ja": "出来事・行事", "cat": "名詞" },
    { "id": 583, "en": "exam", "ja": "試験", "cat": "名詞" },
    { "id": 584, "en": "example", "ja": "例", "cat": "名詞" },
    { "id": 585, "en": "excuse", "ja": "言い訳", "cat": "名詞" },
    { "id": 586, "en": "exercise", "ja": "運動・練習", "cat": "名詞" },
    { "id": 587, "en": "exhibition", "ja": "展示会", "cat": "名詞" },
    { "id": 588, "en": "experience", "ja": "経験", "cat": "名詞" },
    { "id": 589, "en": "expert", "ja": "専門家", "cat": "名詞" },
    { "id": 590, "en": "eye", "ja": "目", "cat": "名詞" },
    { "id": 591, "en": "face", "ja": "顔", "cat": "名詞" },
    { "id": 592, "en": "fact", "ja": "事実", "cat": "名詞" },
    { "id": 593, "en": "factory", "ja": "工場", "cat": "名詞" },
    { "id": 594, "en": "fair", "ja": "品評会・市", "cat": "名詞" },
    { "id": 595, "en": "family", "ja": "家族", "cat": "名詞" },
    { "id": 596, "en": "fan", "ja": "ファン・扇風機", "cat": "名詞" },
    { "id": 597, "en": "farm", "ja": "農場", "cat": "名詞" },
    { "id": 598, "en": "farmer", "ja": "農場主", "cat": "名詞" },
    { "id": 599, "en": "fashion", "ja": "流行", "cat": "名詞" },
    { "id": 600, "en": "father", "ja": "父", "cat": "名詞" },
    { "id": 601, "en": "fault", "ja": "欠点・責任", "cat": "名詞" },
    { "id": 602, "en": "favor", "ja": "親切な行為", "cat": "名詞" },
    { "id": 603, "en": "favorite", "ja": "お気に入り", "cat": "名詞" },
    { "id": 604, "en": "fear", "ja": "恐怖", "cat": "名詞" },
    { "id": 605, "en": "feather", "ja": "羽", "cat": "名詞" },
    { "id": 606, "en": "feeling", "ja": "感情・感覚", "cat": "名詞" },
    { "id": 607, "en": "festival", "ja": "祭り", "cat": "名詞" },
    { "id": 608, "en": "fever", "ja": "熱", "cat": "名詞" },
    { "id": 609, "en": "field", "ja": "野原・競技場", "cat": "名詞" },
    { "id": 610, "en": "fight", "ja": "戦い", "cat": "名詞" },
    { "id": 611, "en": "figure", "ja": "姿・数字", "cat": "名詞" },
    { "id": 612, "en": "film", "ja": "映画", "cat": "名詞" },
    { "id": 613, "en": "final", "ja": "決勝戦", "cat": "名詞" },
    { "id": 614, "en": "finger", "ja": "指", "cat": "名詞" },
    { "id": 615, "en": "fire", "ja": "火・火事", "cat": "名詞" },
    { "id": 616, "en": "fish", "ja": "魚", "cat": "名詞" },
    { "id": 617, "en": "flag", "ja": "旗", "cat": "名詞" },
    { "id": 618, "en": "flight", "ja": "飛行・便", "cat": "名詞" },
    { "id": 619, "en": "floor", "ja": "床・階", "cat": "名詞" },
    { "id": 620, "en": "flower", "ja": "花", "cat": "名詞" },
    { "id": 621, "en": "flu", "ja": "インフルエンザ", "cat": "名詞" },
    { "id": 622, "en": "fog", "ja": "霧", "cat": "名詞" },
    { "id": 623, "en": "food", "ja": "食べ物", "cat": "名詞" },
    { "id": 624, "en": "foot", "ja": "足", "cat": "名詞" },
    { "id": 625, "en": "force", "ja": "力", "cat": "名詞" },
    { "id": 626, "en": "foreign", "ja": "外国の", "cat": "名詞" },
    { "id": 627, "en": "forest", "ja": "森", "cat": "名詞" },
    { "id": 628, "en": "fork", "ja": "フォーク", "cat": "名詞" },
    { "id": 629, "en": "form", "ja": "形・用紙", "cat": "名詞" },
    { "id": 630, "en": "friend", "ja": "友達", "cat": "名詞" },
    { "id": 631, "en": "friendship", "ja": "友情", "cat": "名詞" },
    { "id": 632, "en": "frog", "ja": "カエル", "cat": "名詞" },
    { "id": 633, "en": "front", "ja": "前・正面", "cat": "名詞" },
    { "id": 634, "en": "fruit", "ja": "果物", "cat": "名詞" },
    { "id": 635, "en": "fuel", "ja": "燃料", "cat": "名詞" },
    { "id": 636, "en": "fun", "ja": "楽しみ", "cat": "名詞" },
    { "id": 637, "en": "furniture", "ja": "家具", "cat": "名詞" },
    { "id": 638, "en": "future", "ja": "未来", "cat": "名詞" },
    { "id": 639, "en": "game", "ja": "試合・遊び", "cat": "名詞" },
    { "id": 640, "en": "garage", "ja": "車庫", "cat": "名詞" },
    { "id": 641, "en": "garden", "ja": "庭", "cat": "名詞" },
    { "id": 642, "en": "gas", "ja": "ガス・ガソリン", "cat": "名詞" },
    { "id": 643, "en": "gate", "ja": "門", "cat": "名詞" },
    { "id": 644, "en": "gesture", "ja": "身振り", "cat": "名詞" },
    { "id": 645, "en": "ghost", "ja": "幽霊", "cat": "名詞" },
    { "id": 646, "en": "gift", "ja": "贈り物", "cat": "名詞" },
    { "id": 647, "en": "girl", "ja": "女の子", "cat": "名詞" },
    { "id": 648, "en": "glass", "ja": "コップ・ガラス", "cat": "名詞" },
    { "id": 649, "en": "glasses", "ja": "眼鏡", "cat": "名詞" },
    { "id": 650, "en": "glove", "ja": "手袋", "cat": "名詞" },
    { "id": 651, "en": "goal", "ja": "目標・ゴール", "cat": "名詞" },
    { "id": 652, "en": "god", "ja": "神", "cat": "名詞" },
    { "id": 653, "en": "gold", "ja": "金", "cat": "名詞" },
    { "id": 654, "en": "government", "ja": "政府", "cat": "名詞" },
    { "id": 655, "en": "grade", "ja": "学年・成績", "cat": "名詞" },
    { "id": 656, "en": "grammar", "ja": "文法", "cat": "名詞" },
    { "id": 657, "en": "grandfather", "ja": "祖父", "cat": "名詞" },
    { "id": 658, "en": "grandmother", "ja": "祖母", "cat": "名詞" },
    { "id": 659, "en": "grass", "ja": "草", "cat": "名詞" },
    { "id": 660, "en": "ground", "ja": "地面", "cat": "名詞" },
    { "id": 661, "en": "group", "ja": "集団", "cat": "名詞" },
    { "id": 662, "en": "guest", "ja": "客", "cat": "名詞" },
    { "id": 663, "en": "guide", "ja": "案内人", "cat": "名詞" },
    { "id": 664, "en": "guidebook", "ja": "案内書", "cat": "名詞" },
    { "id": 665, "en": "guitar", "ja": "ギター", "cat": "名詞" },
    { "id": 666, "en": "gym", "ja": "体育館", "cat": "名詞" },
    { "id": 667, "en": "habit", "ja": "習慣・癖", "cat": "名詞" },
    { "id": 668, "en": "hair", "ja": "髪", "cat": "名詞" },
    { "id": 669, "en": "haircut", "ja": "散髪", "cat": "名詞" },
    { "id": 670, "en": "half", "ja": "半分", "cat": "名詞" },
    { "id": 671, "en": "hall", "ja": "会館・廊下", "cat": "名詞" },
    { "id": 672, "en": "hand", "ja": "手", "cat": "名詞" },
    { "id": 673, "en": "handle", "ja": "取っ手", "cat": "名詞" },
    { "id": 674, "en": "happiness", "ja": "幸福", "cat": "名詞" },
    { "id": 675, "en": "hat", "ja": "帽子", "cat": "名詞" },
    { "id": 676, "en": "head", "ja": "頭", "cat": "名詞" },
    { "id": 677, "en": "headache", "ja": "頭痛", "cat": "名詞" },
    { "id": 678, "en": "health", "ja": "健康", "cat": "名詞" },
    { "id": 679, "en": "heart", "ja": "心臓・心", "cat": "名詞" },
    { "id": 680, "en": "heat", "ja": "熱・暑さ", "cat": "名詞" },
    { "id": 681, "en": "heaven", "ja": "天国", "cat": "名詞" },
    { "id": 682, "en": "height", "ja": "高さ・身長", "cat": "名詞" },
    { "id": 683, "en": "helicopter", "ja": "ヘリコプター", "cat": "名詞" },
    { "id": 684, "en": "hello", "ja": "こんにちは", "cat": "名詞" },
    { "id": 685, "en": "help", "ja": "助け", "cat": "名詞" },
    { "id": 686, "en": "hero", "ja": "英雄", "cat": "名詞" },
    { "id": 687, "en": "hill", "ja": "丘", "cat": "名詞" },
    { "id": 688, "en": "history", "ja": "歴史", "cat": "名詞" },
    { "id": 689, "en": "hobby", "ja": "趣味", "cat": "名詞" },
    { "id": 690, "en": "hole", "ja": "穴", "cat": "名詞" },
    { "id": 691, "en": "holiday", "ja": "休日", "cat": "名詞" },
    { "id": 692, "en": "home", "ja": "家・家庭", "cat": "名詞" },
    { "id": 693, "en": "homework", "ja": "宿題", "cat": "名詞" },
    { "id": 694, "en": "honey", "ja": "蜂蜜", "cat": "名詞" },
    { "id": 695, "en": "hope", "ja": "希望", "cat": "名詞" },
    { "id": 696, "en": "horse", "ja": "馬", "cat": "名詞" },
    { "id": 697, "en": "hospital", "ja": "病院", "cat": "名詞" },
    { "id": 698, "en": "host", "ja": "主人・司会者", "cat": "名詞" },
    { "id": 699, "en": "host family", "ja": "ホストファミリー", "cat": "名詞" },
    { "id": 700, "en": "hotel", "ja": "ホテル", "cat": "名詞" },
    { "id": 701, "en": "hour", "ja": "1時間", "cat": "名詞" },
    { "id": 702, "en": "house", "ja": "家", "cat": "名詞" },
    { "id": 703, "en": "housewife", "ja": "主婦", "cat": "名詞" },
    { "id": 704, "en": "human", "ja": "人間", "cat": "名詞" },
    { "id": 705, "en": "husband", "ja": "夫", "cat": "名詞" },
    { "id": 706, "en": "ice", "ja": "氷", "cat": "名詞" },
    { "id": 707, "en": "idea", "ja": "考え", "cat": "名詞" },
    { "id": 708, "en": "illness", "ja": "病気", "cat": "名詞" },
    { "id": 709, "en": "image", "ja": "像・イメージ", "cat": "名詞" },
    { "id": 710, "en": "importance", "ja": "重要性", "cat": "名詞" },
    { "id": 711, "en": "information", "ja": "情報", "cat": "名詞" },
    { "id": 712, "en": "internet", "ja": "インターネット", "cat": "名詞" },
    { "id": 713, "en": "interview", "ja": "面接", "cat": "名詞" },
    { "id": 714, "en": "island", "ja": "島", "cat": "名詞" },
    { "id": 715, "en": "jacket", "ja": "上着", "cat": "名詞" },
    { "id": 716, "en": "jam", "ja": "ジャム", "cat": "名詞" },
    { "id": 717, "en": "job", "ja": "仕事", "cat": "名詞" },
    { "id": 718, "en": "journey", "ja": "旅行", "cat": "名詞" },
    { "id": 719, "en": "juice", "ja": "ジュース", "cat": "名詞" },
    { "id": 720, "en": "key", "ja": "鍵", "cat": "名詞" },
    { "id": 721, "en": "kid", "ja": "子供", "cat": "名詞" },
    { "id": 722, "en": "king", "ja": "王", "cat": "名詞" },
    { "id": 723, "en": "kitchen", "ja": "台所", "cat": "名詞" },
    { "id": 724, "en": "knee", "ja": "膝", "cat": "名詞" },
    { "id": 725, "en": "knife", "ja": "ナイフ", "cat": "名詞" },
    { "id": 726, "en": "lake", "ja": "湖", "cat": "名詞" },
    { "id": 727, "en": "lamp", "ja": "ランプ", "cat": "名詞" },
    { "id": 728, "en": "land", "ja": "土地・陸", "cat": "名詞" },
    { "id": 729, "en": "language", "ja": "言語", "cat": "名詞" },
    { "id": 730, "en": "law", "ja": "法律", "cat": "名詞" },
    { "id": 731, "en": "leaf", "ja": "葉", "cat": "名詞" },
    { "id": 732, "en": "leg", "ja": "脚", "cat": "名詞" },
    { "id": 733, "en": "lesson", "ja": "授業", "cat": "名詞" },
    { "id": 734, "en": "letter", "ja": "手紙・文字", "cat": "名詞" },
    { "id": 735, "en": "library", "ja": "図書館", "cat": "名詞" },
    { "id": 736, "en": "life", "ja": "生活・命", "cat": "名詞" },
    { "id": 737, "en": "light", "ja": "光・明かり", "cat": "名詞" },
    { "id": 738, "en": "line", "ja": "線・列", "cat": "名詞" },
    { "id": 739, "en": "lion", "ja": "ライオン", "cat": "名詞" },
    { "id": 740, "en": "list", "ja": "一覧表", "cat": "名詞" },
    { "id": 741, "en": "lock", "ja": "錠", "cat": "名詞" },
    { "id": 742, "en": "luck", "ja": "運", "cat": "名詞" },
    { "id": 743, "en": "lunch", "ja": "昼食", "cat": "名詞" },
    { "id": 744, "en": "machine", "ja": "機械", "cat": "名詞" },
    { "id": 745, "en": "magazine", "ja": "雑誌", "cat": "名詞" },
    { "id": 746, "en": "mail", "ja": "郵便", "cat": "名詞" },
    { "id": 747, "en": "man", "ja": "男性", "cat": "名詞" },
    { "id": 748, "en": "manager", "ja": "支配人", "cat": "名詞" },
    { "id": 749, "en": "map", "ja": "地図", "cat": "名詞" },
    { "id": 750, "en": "market", "ja": "市場", "cat": "名詞" },
    { "id": 751, "en": "master", "ja": "主人・修士", "cat": "名詞" },
    { "id": 752, "en": "match", "ja": "試合", "cat": "名詞" },
    { "id": 753, "en": "material", "ja": "材料", "cat": "名詞" },
    { "id": 754, "en": "matter", "ja": "事柄・問題", "cat": "名詞" },
    { "id": 755, "en": "meal", "ja": "食事", "cat": "名詞" },
    { "id": 756, "en": "meat", "ja": "肉", "cat": "名詞" },
    { "id": 757, "en": "medicine", "ja": "薬・医学", "cat": "名詞" },
    { "id": 758, "en": "meeting", "ja": "会議", "cat": "名詞" },
    { "id": 759, "en": "member", "ja": "一員", "cat": "名詞" },
    { "id": 760, "en": "memory", "ja": "記憶", "cat": "名詞" },
    { "id": 761, "en": "menu", "ja": "献立表", "cat": "名詞" },
    { "id": 762, "en": "message", "ja": "伝言", "cat": "名詞" },
    { "id": 763, "en": "meter", "ja": "メートル", "cat": "名詞" },
    { "id": 764, "en": "middle", "ja": "真ん中", "cat": "名詞" },
    { "id": 765, "en": "midnight", "ja": "真夜中", "cat": "名詞" },
    { "id": 766, "en": "milk", "ja": "牛乳", "cat": "名詞" },
    { "id": 767, "en": "mind", "ja": "心", "cat": "名詞" },
    { "id": 768, "en": "minute", "ja": "分", "cat": "名詞" },
    { "id": 769, "en": "mirror", "ja": "鏡", "cat": "名詞" },
    { "id": 770, "en": "mistake", "ja": "間違い", "cat": "名詞" },
    { "id": 771, "en": "model", "ja": "模型・手本", "cat": "名詞" },
    { "id": 772, "en": "moment", "ja": "瞬間", "cat": "名詞" },
    { "id": 773, "en": "money", "ja": "お金", "cat": "名詞" },
    { "id": 774, "en": "monkey", "ja": "サル", "cat": "名詞" },
    { "id": 775, "en": "month", "ja": "月", "cat": "名詞" },
    { "id": 776, "en": "moon", "ja": "月(天体)", "cat": "名詞" },
    { "id": 777, "en": "morning", "ja": "朝", "cat": "名詞" },
    { "id": 778, "en": "mother", "ja": "母", "cat": "名詞" },
    { "id": 779, "en": "mountain", "ja": "山", "cat": "名詞" },
    { "id": 780, "en": "mouse", "ja": "ネズミ", "cat": "名詞" },
    { "id": 781, "en": "mouth", "ja": "口", "cat": "名詞" },
    { "id": 782, "en": "movie", "ja": "映画", "cat": "名詞" },
    { "id": 783, "en": "museum", "ja": "博物館", "cat": "名詞" },
    { "id": 784, "en": "music", "ja": "音楽", "cat": "名詞" },
    { "id": 785, "en": "musician", "ja": "音楽家", "cat": "名詞" },
    { "id": 786, "en": "name", "ja": "名前", "cat": "名詞" },
    { "id": 787, "en": "nation", "ja": "国家", "cat": "名詞" },
    { "id": 788, "en": "nature", "ja": "自然", "cat": "名詞" },
    { "id": 789, "en": "neck", "ja": "首", "cat": "名詞" },
    { "id": 790, "en": "necklace", "ja": "ネックレス", "cat": "名詞" },
    { "id": 791, "en": "neighbor", "ja": "近所の人", "cat": "名詞" },
    { "id": 792, "en": "news", "ja": "知らせ", "cat": "名詞" },
    { "id": 793, "en": "newspaper", "ja": "新聞", "cat": "名詞" },
    { "id": 794, "en": "night", "ja": "夜", "cat": "名詞" },
    { "id": 795, "en": "noise", "ja": "騒音", "cat": "名詞" },
    { "id": 796, "en": "noon", "ja": "正午", "cat": "名詞" },
    { "id": 797, "en": "north", "ja": "北", "cat": "名詞" },
    { "id": 798, "en": "nose", "ja": "鼻", "cat": "名詞" },
    { "id": 799, "en": "note", "ja": "メモ", "cat": "名詞" },
    { "id": 800, "en": "notebook", "ja": "ノート", "cat": "名詞" },
    { "id": 801, "en": "number", "ja": "数", "cat": "名詞" },
    { "id": 802, "en": "nurse", "ja": "看護師", "cat": "名詞" },
    { "id": 803, "en": "ocean", "ja": "大洋", "cat": "名詞" },
    { "id": 804, "en": "office", "ja": "事務所", "cat": "名詞" },
    { "id": 805, "en": "officer", "ja": "警官・役人", "cat": "名詞" },
    { "id": 806, "en": "oil", "ja": "油", "cat": "名詞" },
    { "id": 807, "en": "onion", "ja": "タマネギ", "cat": "名詞" },
    { "id": 808, "en": "opinion", "ja": "意見", "cat": "名詞" },
    { "id": 809, "en": "orange", "ja": "オレンジ", "cat": "名詞" },
    { "id": 810, "en": "order", "ja": "注文・順序", "cat": "名詞" },
    { "id": 811, "en": "page", "ja": "ページ", "cat": "名詞" },
    { "id": 812, "en": "pain", "ja": "痛み", "cat": "名詞" },
    { "id": 813, "en": "pair", "ja": "一対", "cat": "名詞" },
    { "id": 814, "en": "paper", "ja": "紙", "cat": "名詞" },
    { "id": 815, "en": "parent", "ja": "親", "cat": "名詞" },
    { "id": 816, "en": "park", "ja": "公園", "cat": "名詞" },
    { "id": 817, "en": "part", "ja": "部分", "cat": "名詞" },
    { "id": 818, "en": "party", "ja": "パーティー", "cat": "名詞" },
    { "id": 819, "en": "passenger", "ja": "乗客", "cat": "名詞" },
    { "id": 820, "en": "passport", "ja": "旅券", "cat": "名詞" },
    { "id": 821, "en": "past", "ja": "過去", "cat": "名詞" },
    { "id": 822, "en": "peace", "ja": "平和", "cat": "名詞" },
    { "id": 823, "en": "pen", "ja": "ペン", "cat": "名詞" },
    { "id": 824, "en": "pencil", "ja": "鉛筆", "cat": "名詞" },
    { "id": 825, "en": "people", "ja": "人々", "cat": "名詞" },
    { "id": 826, "en": "percent", "ja": "パーセント", "cat": "名詞" },
    { "id": 827, "en": "person", "ja": "人", "cat": "名詞" },
    { "id": 828, "en": "pet", "ja": "ペット", "cat": "名詞" },
    { "id": 829, "en": "phone", "ja": "電話", "cat": "名詞" },
    { "id": 830, "en": "photo", "ja": "写真", "cat": "名詞" },
    { "id": 831, "en": "piano", "ja": "ピアノ", "cat": "名詞" },
    { "id": 832, "en": "picnic", "ja": "ピクニック", "cat": "名詞" },
    { "id": 833, "en": "picture", "ja": "絵・写真", "cat": "名詞" },
    { "id": 834, "en": "piece", "ja": "一個・一片", "cat": "名詞" },
    { "id": 835, "en": "pilot", "ja": "パイロット", "cat": "名詞" },
    { "id": 836, "en": "place", "ja": "場所", "cat": "名詞" },
    { "id": 837, "en": "plan", "ja": "計画", "cat": "名詞" },
    { "id": 838, "en": "plane", "ja": "飛行機", "cat": "名詞" },
    { "id": 839, "en": "plant", "ja": "植物", "cat": "名詞" },
    { "id": 840, "en": "plastic", "ja": "プラスチック", "cat": "名詞" },
    { "id": 841, "en": "plate", "ja": "皿", "cat": "名詞" },
    { "id": 842, "en": "platform", "ja": "ホーム", "cat": "名詞" },
    { "id": 843, "en": "player", "ja": "選手", "cat": "名詞" },
    { "id": 844, "en": "pocket", "ja": "ポケット", "cat": "名詞" },
    { "id": 845, "en": "poem", "ja": "詩", "cat": "名詞" },
    { "id": 846, "en": "point", "ja": "点・要点", "cat": "名詞" },
    { "id": 847, "en": "police", "ja": "警察", "cat": "名詞" },
    { "id": 848, "en": "pool", "ja": "プール", "cat": "名詞" },
    { "id": 849, "en": "population", "ja": "人口", "cat": "名詞" },
    { "id": 850, "en": "pork", "ja": "豚肉", "cat": "名詞" },
    { "id": 851, "en": "port", "ja": "港", "cat": "名詞" },
    { "id": 852, "en": "post", "ja": "郵便・柱", "cat": "名詞" },
    { "id": 853, "en": "postcard", "ja": "絵葉書", "cat": "名詞" },
    { "id": 854, "en": "poster", "ja": "ポスター", "cat": "名詞" },
    { "id": 855, "en": "potato", "ja": "ジャガイモ", "cat": "名詞" },
    { "id": 856, "en": "power", "ja": "力", "cat": "名詞" },
    { "id": 857, "en": "practice", "ja": "練習", "cat": "名詞" },
    { "id": 858, "en": "present", "ja": "プレゼント", "cat": "名詞" },
    { "id": 859, "en": "president", "ja": "大統領・社長", "cat": "名詞" },
    { "id": 860, "en": "price", "ja": "価格", "cat": "名詞" },
    { "id": 861, "en": "prince", "ja": "王子", "cat": "名詞" },
    { "id": 862, "en": "princess", "ja": "王女", "cat": "名詞" },
    { "id": 863, "en": "prize", "ja": "賞", "cat": "名詞" },
    { "id": 864, "en": "problem", "ja": "問題", "cat": "名詞" },
    { "id": 865, "en": "program", "ja": "番組・計画", "cat": "名詞" },
    { "id": 866, "en": "project", "ja": "計画・事業", "cat": "名詞" },
    { "id": 867, "en": "promise", "ja": "約束", "cat": "名詞" },
    { "id": 868, "en": "purpose", "ja": "目的", "cat": "名詞" },
    { "id": 869, "en": "purse", "ja": "財布", "cat": "名詞" },
    { "id": 870, "en": "question", "ja": "質問", "cat": "名詞" },
    { "id": 871, "en": "quiz", "ja": "クイズ", "cat": "名詞" },
    { "id": 872, "en": "rabbit", "ja": "ウサギ", "cat": "名詞" },
    { "id": 873, "en": "race", "ja": "競争", "cat": "名詞" },
    { "id": 874, "en": "radio", "ja": "ラジオ", "cat": "名詞" },
    { "id": 875, "en": "rain", "ja": "雨", "cat": "名詞" },
    { "id": 876, "en": "rainbow", "ja": "虹", "cat": "名詞" },
    { "id": 877, "en": "reason", "ja": "理由", "cat": "名詞" },
    { "id": 878, "en": "receipt", "ja": "領収書", "cat": "名詞" },
    { "id": 879, "en": "record", "ja": "記録", "cat": "名詞" },
    { "id": 880, "en": "refrigerator", "ja": "冷蔵庫", "cat": "名詞" },
    { "id": 881, "en": "report", "ja": "報告", "cat": "名詞" },
    { "id": 882, "en": "rest", "ja": "休憩・残り", "cat": "名詞" },
    { "id": 883, "en": "restaurant", "ja": "レストラン", "cat": "名詞" },
    { "id": 884, "en": "result", "ja": "結果", "cat": "名詞" },
    { "id": 885, "en": "ribbon", "ja": "リボン", "cat": "名詞" },
    { "id": 886, "en": "rice", "ja": "米", "cat": "名詞" },
    { "id": 887, "en": "ride", "ja": "乗ること", "cat": "名詞" },
    { "id": 888, "en": "ring", "ja": "指輪", "cat": "名詞" },
    { "id": 889, "en": "river", "ja": "川", "cat": "名詞" },
    { "id": 890, "en": "road", "ja": "道路", "cat": "名詞" },
    { "id": 891, "en": "robot", "ja": "ロボット", "cat": "名詞" },
    { "id": 892, "en": "rock", "ja": "岩", "cat": "名詞" },
    { "id": 893, "en": "roof", "ja": "屋根", "cat": "名詞" },
    { "id": 894, "en": "room", "ja": "部屋", "cat": "名詞" },
    { "id": 895, "en": "rope", "ja": "ロープ", "cat": "名詞" },
    { "id": 896, "en": "rose", "ja": "バラ", "cat": "名詞" },
    { "id": 897, "en": "rule", "ja": "規則", "cat": "名詞" },
    { "id": 898, "en": "salad", "ja": "サラダ", "cat": "名詞" },
    { "id": 899, "en": "sale", "ja": "販売・特売", "cat": "名詞" },
    { "id": 900, "en": "salt", "ja": "塩", "cat": "名詞" },
    { "id": 901, "en": "sand", "ja": "砂", "cat": "名詞" },
    { "id": 902, "en": "sandwich", "ja": "サンドイッチ", "cat": "名詞" },
    { "id": 903, "en": "sauce", "ja": "ソース", "cat": "名詞" },
    { "id": 904, "en": "scene", "ja": "場面", "cat": "名詞" },
    { "id": 905, "en": "schedule", "ja": "予定", "cat": "名詞" },
    { "id": 906, "en": "school", "ja": "学校", "cat": "名詞" },
    { "id": 907, "en": "science", "ja": "科学", "cat": "名詞" },
    { "id": 908, "en": "scientist", "ja": "科学者", "cat": "名詞" },
    { "id": 909, "en": "screen", "ja": "画面", "cat": "名詞" },
    { "id": 910, "en": "sea", "ja": "海", "cat": "名詞" },
    { "id": 911, "en": "season", "ja": "季節", "cat": "名詞" },
    { "id": 912, "en": "seat", "ja": "座席", "cat": "名詞" },
    { "id": 913, "en": "secret", "ja": "秘密", "cat": "名詞" },
    { "id": 914, "en": "secretary", "ja": "秘書", "cat": "名詞" },
    { "id": 915, "en": "section", "ja": "部分", "cat": "名詞" },
    { "id": 916, "en": "sentence", "ja": "文", "cat": "名詞" },
    { "id": 917, "en": "service", "ja": "サービス", "cat": "名詞" },
    { "id": 918, "en": "shade", "ja": "陰", "cat": "名詞" },
    { "id": 919, "en": "shadow", "ja": "影", "cat": "名詞" },
    { "id": 920, "en": "shape", "ja": "形", "cat": "名詞" },
    { "id": 921, "en": "sheep", "ja": "羊", "cat": "名詞" },
    { "id": 922, "en": "ship", "ja": "船", "cat": "名詞" },
    { "id": 923, "en": "shirt", "ja": "シャツ", "cat": "名詞" },
    { "id": 924, "en": "shoes", "ja": "靴", "cat": "名詞" },
    { "id": 925, "en": "shop", "ja": "店", "cat": "名詞" },
    { "id": 926, "en": "side", "ja": "側・側面", "cat": "名詞" },
    { "id": 927, "en": "sight", "ja": "視力・光景", "cat": "名詞" },
    { "id": 928, "en": "sign", "ja": "標識・合図", "cat": "名詞" },
    { "id": 929, "en": "singer", "ja": "歌手", "cat": "名詞" },
    { "id": 930, "en": "sister", "ja": "姉・妹", "cat": "名詞" },
    { "id": 931, "en": "size", "ja": "大きさ", "cat": "名詞" },
    { "id": 932, "en": "sky", "ja": "空", "cat": "名詞" },
    { "id": 933, "en": "smile", "ja": "微笑み", "cat": "名詞" },
    { "id": 934, "en": "smoke", "ja": "煙", "cat": "名詞" },
    { "id": 935, "en": "snake", "ja": "ヘビ", "cat": "名詞" },
    { "id": 936, "en": "snow", "ja": "雪", "cat": "名詞" },
    { "id": 937, "en": "soccer", "ja": "サッカー", "cat": "名詞" },
    { "id": 938, "en": "society", "ja": "社会", "cat": "名詞" },
    { "id": 939, "en": "socks", "ja": "靴下", "cat": "名詞" },
    { "id": 940, "en": "sofa", "ja": "ソファー", "cat": "名詞" },
    { "id": 941, "en": "son", "ja": "息子", "cat": "名詞" },
    { "id": 942, "en": "song", "ja": "歌", "cat": "名詞" },
    { "id": 943, "en": "sound", "ja": "音", "cat": "名詞" },
    { "id": 944, "en": "soup", "ja": "スープ", "cat": "名詞" },
    { "id": 945, "en": "south", "ja": "南", "cat": "名詞" },
    { "id": 946, "en": "space", "ja": "宇宙・空間", "cat": "名詞" },
    { "id": 947, "en": "speech", "ja": "演説", "cat": "名詞" },
    { "id": 948, "en": "sport", "ja": "スポーツ", "cat": "名詞" },
    { "id": 949, "en": "spring", "ja": "春・泉", "cat": "名詞" },
    { "id": 950, "en": "stadium", "ja": "競技場", "cat": "名詞" },
    { "id": 951, "en": "stage", "ja": "舞台", "cat": "名詞" },
    { "id": 952, "en": "stamp", "ja": "切手", "cat": "名詞" },
    { "id": 953, "en": "star", "ja": "星・スター", "cat": "名詞" },
    { "id": 954, "en": "station", "ja": "駅", "cat": "名詞" },
    { "id": 955, "en": "steak", "ja": "ステーキ", "cat": "名詞" },
    { "id": 956, "en": "step", "ja": "歩み・段階", "cat": "名詞" },
    { "id": 957, "en": "stone", "ja": "石", "cat": "名詞" },
    { "id": 958, "en": "store", "ja": "店", "cat": "名詞" },
    { "id": 959, "en": "story", "ja": "物語・話", "cat": "名詞" },
    { "id": 960, "en": "street", "ja": "通り", "cat": "名詞" },
    { "id": 961, "en": "student", "ja": "生徒", "cat": "名詞" },
    { "id": 962, "en": "subject", "ja": "教科・主題", "cat": "名詞" },
    { "id": 963, "en": "subway", "ja": "地下鉄", "cat": "名詞" },
    { "id": 964, "en": "summer", "ja": "夏", "cat": "名詞" },
    { "id": 965, "en": "sun", "ja": "太陽", "cat": "名詞" },
    { "id": 966, "en": "supermarket", "ja": "スーパー", "cat": "名詞" },
    { "id": 967, "en": "sweater", "ja": "セーター", "cat": "名詞" },
    { "id": 968, "en": "swimming", "ja": "水泳", "cat": "名詞" },
    { "id": 969, "en": "table", "ja": "テーブル", "cat": "名詞" },
    { "id": 970, "en": "taxi", "ja": "タクシー", "cat": "名詞" },
    { "id": 971, "en": "tea", "ja": "お茶", "cat": "名詞" },
    { "id": 972, "en": "teacher", "ja": "先生", "cat": "名詞" },
    { "id": 973, "en": "team", "ja": "チーム", "cat": "名詞" },
    { "id": 974, "en": "technology", "ja": "科学技術", "cat": "名詞" },
    { "id": 975, "en": "telephone", "ja": "電話", "cat": "名詞" },
    { "id": 976, "en": "temperature", "ja": "温度・気温", "cat": "名詞" },
    { "id": 977, "en": "tennis", "ja": "テニス", "cat": "名詞" },
    { "id": 978, "en": "test", "ja": "試験", "cat": "名詞" },
    { "id": 979, "en": "textbook", "ja": "教科書", "cat": "名詞" },
    { "id": 980, "en": "theater", "ja": "劇場", "cat": "名詞" },
    { "id": 981, "en": "thing", "ja": "物・事", "cat": "名詞" },
    { "id": 982, "en": "ticket", "ja": "切符", "cat": "名詞" },
    { "id": 983, "en": "time", "ja": "時・回", "cat": "名詞" },
    { "id": 984, "en": "today", "ja": "今日", "cat": "名詞" },
    { "id": 985, "en": "toilet", "ja": "トイレ", "cat": "名詞" },
    { "id": 986, "en": "tomato", "ja": "トマト", "cat": "名詞" },
    { "id": 987, "en": "tomorrow", "ja": "明日", "cat": "名詞" },
    { "id": 988, "en": "tooth", "ja": "歯", "cat": "名詞" },
    { "id": 989, "en": "top", "ja": "頂上", "cat": "名詞" },
    { "id": 990, "en": "tour", "ja": "旅行", "cat": "名詞" },
    { "id": 991, "en": "tourist", "ja": "観光客", "cat": "名詞" },
    { "id": 992, "en": "towel", "ja": "タオル", "cat": "名詞" },
    { "id": 993, "en": "town", "ja": "町", "cat": "名詞" },
    { "id": 994, "en": "toy", "ja": "おもちゃ", "cat": "名詞" },
    { "id": 995, "en": "traffic", "ja": "交通", "cat": "名詞" },
    { "id": 996, "en": "train", "ja": "電車", "cat": "名詞" },
    { "id": 997, "en": "travel", "ja": "旅行", "cat": "名詞" },
    { "id": 998, "en": "tree", "ja": "木", "cat": "名詞" },
    { "id": 999, "en": "trip", "ja": "旅行", "cat": "名詞" },
    { "id": 1000, "en": "trouble", "ja": "困難・揉め事", "cat": "名詞" },
    { "id": 1001, "en": "truck", "ja": "トラック", "cat": "名詞" },
    { "id": 1002, "en": "t-shirt", "ja": "Tシャツ", "cat": "名詞" },
    { "id": 1003, "en": "umbrella", "ja": "傘", "cat": "名詞" },
    { "id": 1004, "en": "uncle", "ja": "おじ", "cat": "名詞" },
    { "id": 1005, "en": "uniform", "ja": "制服", "cat": "名詞" },
    { "id": 1006, "en": "university", "ja": "大学", "cat": "名詞" },
    { "id": 1007, "en": "vacation", "ja": "休暇", "cat": "名詞" },
    { "id": 1008, "en": "vegetable", "ja": "野菜", "cat": "名詞" },
    { "id": 1009, "en": "video", "ja": "ビデオ", "cat": "名詞" },
    { "id": 1010, "en": "village", "ja": "村", "cat": "名詞" },
    { "id": 1011, "en": "violin", "ja": "バイオリン", "cat": "名詞" },
    { "id": 1012, "en": "visit", "ja": "訪問", "cat": "名詞" },
    { "id": 1013, "en": "voice", "ja": "声", "cat": "名詞" },
    { "id": 1014, "en": "volunteer", "ja": "ボランティア", "cat": "名詞" },
    { "id": 1015, "en": "wall", "ja": "壁", "cat": "名詞" },
    { "id": 1016, "en": "wallet", "ja": "財布", "cat": "名詞" },
    { "id": 1017, "en": "war", "ja": "戦争", "cat": "名詞" },
    { "id": 1018, "en": "water", "ja": "水", "cat": "名詞" },
    { "id": 1019, "en": "way", "ja": "道・方法", "cat": "名詞" },
    { "id": 1020, "en": "weather", "ja": "天気", "cat": "名詞" },
    { "id": 1021, "en": "week", "ja": "週", "cat": "名詞" },
    { "id": 1022, "en": "weekend", "ja": "週末", "cat": "名詞" },
    { "id": 1023, "en": "weight", "ja": "重さ", "cat": "名詞" },
    { "id": 1024, "en": "west", "ja": "西", "cat": "名詞" },
    { "id": 1025, "en": "whale", "ja": "クジラ", "cat": "名詞" },
    { "id": 1026, "en": "wife", "ja": "妻", "cat": "名詞" },
    { "id": 1027, "en": "wind", "ja": "風", "cat": "名詞" },
    { "id": 1028, "en": "window", "ja": "窓", "cat": "名詞" },
    { "id": 1029, "en": "winter", "ja": "冬", "cat": "名詞" },
    { "id": 1030, "en": "woman", "ja": "女性", "cat": "名詞" },
    { "id": 1031, "en": "wood", "ja": "木材・森", "cat": "名詞" },
    { "id": 1032, "en": "word", "ja": "単語・言葉", "cat": "名詞" },
    { "id": 1033, "en": "work", "ja": "仕事", "cat": "名詞" },
    { "id": 1034, "en": "world", "ja": "世界", "cat": "名詞" },
    { "id": 1035, "en": "writer", "ja": "作家", "cat": "名詞" },
    { "id": 1036, "en": "year", "ja": "年", "cat": "名詞" },
    { "id": 1037, "en": "yesterday", "ja": "昨日", "cat": "名詞" },
    { "id": 1038, "en": "zoo", "ja": "動物園", "cat": "名詞" },
    { "id": 1101, "en": "able", "ja": "可能な", "cat": "形容詞" },
    { "id": 1102, "en": "about", "ja": "約・〜について", "cat": "副詞" },
    { "id": 1103, "en": "abroad", "ja": "海外へ", "cat": "副詞" },
    { "id": 1104, "en": "actually", "ja": "実は", "cat": "副詞" },
    { "id": 1105, "en": "afraid", "ja": "恐れて", "cat": "形容詞" },
    { "id": 1106, "en": "again", "ja": "再び", "cat": "副詞" },
    { "id": 1107, "en": "ago", "ja": "〜前に", "cat": "副詞" },
    { "id": 1108, "en": "all", "ja": "すべての", "cat": "形容詞" },
    { "id": 1109, "en": "almost", "ja": "ほとんど", "cat": "副詞" },
    { "id": 1110, "en": "alone", "ja": "一人で", "cat": "副詞" },
    { "id": 1111, "en": "already", "ja": "すでに", "cat": "副詞" },
    { "id": 1112, "en": "also", "ja": "〜もまた", "cat": "副詞" },
    { "id": 1113, "en": "always", "ja": "いつも", "cat": "副詞" },
    { "id": 1114, "en": "angry", "ja": "怒った", "cat": "形容詞" },
    { "id": 1115, "en": "another", "ja": "もう一つの", "cat": "形容詞" },
    { "id": 1116, "en": "any", "ja": "いくつかの", "cat": "形容詞" },
    { "id": 1117, "en": "around", "ja": "周りに", "cat": "副詞" },
    { "id": 1118, "en": "asleep", "ja": "眠って", "cat": "形容詞" },
    { "id": 1119, "en": "available", "ja": "利用できる", "cat": "形容詞" },
    { "id": 1120, "en": "away", "ja": "離れて", "cat": "副詞" },
    { "id": 1121, "en": "bad", "ja": "悪い", "cat": "形容詞" },
    { "id": 1122, "en": "beautiful", "ja": "美しい", "cat": "形容詞" },
    { "id": 1123, "en": "best", "ja": "最も良い", "cat": "形容詞" },
    { "id": 1124, "en": "better", "ja": "より良い", "cat": "形容詞" },
    { "id": 1125, "en": "big", "ja": "大きい", "cat": "形容詞" },
    { "id": 1126, "en": "boring", "ja": "退屈な", "cat": "形容詞" },
    { "id": 1127, "en": "born", "ja": "生まれた", "cat": "形容詞" },
    { "id": 1128, "en": "both", "ja": "両方の", "cat": "形容詞" },
    { "id": 1129, "en": "brave", "ja": "勇敢な", "cat": "形容詞" },
    { "id": 1130, "en": "bright", "ja": "明るい", "cat": "形容詞" },
    { "id": 1131, "en": "busy", "ja": "忙しい", "cat": "形容詞" },
    { "id": 1132, "en": "careful", "ja": "注意深い", "cat": "形容詞" },
    { "id": 1133, "en": "cheap", "ja": "安い", "cat": "形容詞" },
    { "id": 1134, "en": "clean", "ja": "清潔な", "cat": "形容詞" },
    { "id": 1135, "en": "clear", "ja": "晴れた・明白な", "cat": "形容詞" },
    { "id": 1136, "en": "clever", "ja": "賢い", "cat": "形容詞" },
    { "id": 1137, "en": "close", "ja": "近い", "cat": "形容詞" },
    { "id": 1138, "en": "cloudy", "ja": "曇った", "cat": "形容詞" },
    { "id": 1139, "en": "cold", "ja": "寒い", "cat": "形容詞" },
    { "id": 1140, "en": "comfortable", "ja": "快適な", "cat": "形容詞" },
    { "id": 1141, "en": "common", "ja": "共通の・普通の", "cat": "形容詞" },
    { "id": 1142, "en": "cool", "ja": "涼しい", "cat": "形容詞" },
    { "id": 1143, "en": "correct", "ja": "正しい", "cat": "形容詞" },
    { "id": 1144, "en": "cute", "ja": "かわいい", "cat": "形容詞" },
    { "id": 1145, "en": "dangerous", "ja": "危険な", "cat": "形容詞" },
    { "id": 1146, "en": "dark", "ja": "暗い", "cat": "形容詞" },
    { "id": 1147, "en": "dead", "ja": "死んだ", "cat": "形容詞" },
    { "id": 1148, "en": "dear", "ja": "親愛なる", "cat": "形容詞" },
    { "id": 1149, "en": "deep", "ja": "深い", "cat": "形容詞" },
    { "id": 1150, "en": "delicious", "ja": "美味しい", "cat": "形容詞" },
    { "id": 1151, "en": "different", "ja": "異なる", "cat": "形容詞" },
    { "id": 1152, "en": "difficult", "ja": "難しい", "cat": "形容詞" },
    { "id": 1153, "en": "dirty", "ja": "汚い", "cat": "形容詞" },
    { "id": 1154, "en": "dry", "ja": "乾いた", "cat": "形容詞" },
    { "id": 1155, "en": "early", "ja": "早い", "cat": "形容詞" },
    { "id": 1156, "en": "easy", "ja": "簡単な", "cat": "形容詞" },
    { "id": 1157, "en": "either", "ja": "どちらかの", "cat": "形容詞" },
    { "id": 1158, "en": "else", "ja": "他に", "cat": "副詞" },
    { "id": 1159, "en": "empty", "ja": "空の", "cat": "形容詞" },
    { "id": 1160, "en": "enough", "ja": "十分な", "cat": "形容詞" },
    { "id": 1161, "en": "even", "ja": "〜でさえ", "cat": "副詞" },
    { "id": 1162, "en": "ever", "ja": "これまでに", "cat": "副詞" },
    { "id": 1163, "en": "excited", "ja": "興奮した", "cat": "形容詞" },
    { "id": 1164, "en": "exciting", "ja": "わくわくさせる", "cat": "形容詞" },
    { "id": 1165, "en": "expensive", "ja": "高価な", "cat": "形容詞" },
    { "id": 1166, "en": "famous", "ja": "有名な", "cat": "形容詞" },
    { "id": 1167, "en": "far", "ja": "遠い", "cat": "形容詞" },
    { "id": 1168, "en": "fast", "ja": "速い", "cat": "形容詞" },
    { "id": 1169, "en": "fat", "ja": "太った", "cat": "形容詞" },
    { "id": 1170, "en": "favorite", "ja": "お気に入りの", "cat": "形容詞" },
    { "id": 1171, "en": "few", "ja": "少数の", "cat": "形容詞" },
    { "id": 1172, "en": "final", "ja": "最後の", "cat": "形容詞" },
    { "id": 1173, "en": "fine", "ja": "元気な・晴れた", "cat": "形容詞" },
    { "id": 1174, "en": "first", "ja": "最初の", "cat": "形容詞" },
    { "id": 1175, "en": "foreign", "ja": "外国の", "cat": "形容詞" },
    { "id": 1176, "en": "free", "ja": "自由な・無料の", "cat": "形容詞" },
    { "id": 1177, "en": "fresh", "ja": "新鮮な", "cat": "形容詞" },
    { "id": 1178, "en": "friendly", "ja": "親しみやすい", "cat": "形容詞" },
    { "id": 1179, "en": "full", "ja": "満杯の", "cat": "形容詞" },
    { "id": 1180, "en": "funny", "ja": "面白い", "cat": "形容詞" },
    { "id": 1181, "en": "glad", "ja": "うれしい", "cat": "形容詞" },
    { "id": 1182, "en": "good", "ja": "良い", "cat": "形容詞" },
    { "id": 1183, "en": "great", "ja": "素晴らしい", "cat": "形容詞" },
    { "id": 1184, "en": "happy", "ja": "幸せな", "cat": "形容詞" },
    { "id": 1185, "en": "hard", "ja": "硬い・難しい", "cat": "形容詞" },
    { "id": 1186, "en": "healthy", "ja": "健康な", "cat": "形容詞" },
    { "id": 1187, "en": "heavy", "ja": "重い", "cat": "形容詞" },
    { "id": 1188, "en": "high", "ja": "高い", "cat": "形容詞" },
    { "id": 1189, "en": "hot", "ja": "暑い", "cat": "形容詞" },
    { "id": 1190, "en": "how", "ja": "どのように", "cat": "副詞" },
    { "id": 1191, "en": "hungry", "ja": "空腹の", "cat": "形容詞" },
    { "id": 1192, "en": "ill", "ja": "病気で", "cat": "形容詞" },
    { "id": 1193, "en": "important", "ja": "重要な", "cat": "形容詞" },
    { "id": 1194, "en": "impossible", "ja": "不可能な", "cat": "形容詞" },
    { "id": 1195, "en": "interested", "ja": "興味がある", "cat": "形容詞" },
    { "id": 1196, "en": "interesting", "ja": "面白い", "cat": "形容詞" },
    { "id": 1197, "en": "international", "ja": "国際的な", "cat": "形容詞" },
    { "id": 1198, "en": "just", "ja": "ちょうど", "cat": "副詞" },
    { "id": 1199, "en": "kind", "ja": "親切な", "cat": "形容詞" },
    { "id": 1200, "en": "large", "ja": "大きい", "cat": "形容詞" },
    { "id": 1201, "en": "last", "ja": "最後の", "cat": "形容詞" },
    { "id": 1202, "en": "late", "ja": "遅い", "cat": "形容詞" },
    { "id": 1203, "en": "later", "ja": "後で", "cat": "副詞" },
    { "id": 1204, "en": "left", "ja": "左の", "cat": "形容詞" },
    { "id": 1205, "en": "little", "ja": "小さい", "cat": "形容詞" },
    { "id": 1206, "en": "long", "ja": "長い", "cat": "形容詞" },
    { "id": 1207, "en": "loud", "ja": "大声の", "cat": "形容詞" },
    { "id": 1208, "en": "low", "ja": "低い", "cat": "形容詞" },
    { "id": 1209, "en": "lucky", "ja": "運が良い", "cat": "形容詞" },
    { "id": 1210, "en": "main", "ja": "主な", "cat": "形容詞" },
    { "id": 1211, "en": "many", "ja": "多くの", "cat": "形容詞" },
    { "id": 1212, "en": "maybe", "ja": "たぶん", "cat": "副詞" },
    { "id": 1213, "en": "more", "ja": "もっと", "cat": "副詞" },
    { "id": 1214, "en": "most", "ja": "最も", "cat": "副詞" },
    { "id": 1215, "en": "much", "ja": "たくさんの", "cat": "形容詞" },
    { "id": 1216, "en": "national", "ja": "国家の", "cat": "形容詞" },
    { "id": 1217, "en": "near", "ja": "近い", "cat": "形容詞" },
    { "id": 1218, "en": "necessary", "ja": "必要な", "cat": "形容詞" },
    { "id": 1219, "en": "nervous", "ja": "緊張して", "cat": "形容詞" },
    { "id": 1220, "en": "never", "ja": "決して〜ない", "cat": "副詞" },
    { "id": 1221, "en": "new", "ja": "新しい", "cat": "形容詞" },
    { "id": 1222, "en": "next", "ja": "次の", "cat": "形容詞" },
    { "id": 1223, "en": "nice", "ja": "素敵な", "cat": "形容詞" },
    { "id": 1224, "en": "noisy", "ja": "騒がしい", "cat": "形容詞" },
    { "id": 1225, "en": "now", "ja": "今", "cat": "副詞" },
    { "id": 1226, "en": "off", "ja": "離れて", "cat": "副詞" },
    { "id": 1227, "en": "often", "ja": "しばしば", "cat": "副詞" },
    { "id": 1228, "en": "old", "ja": "古い・年とった", "cat": "形容詞" },
    { "id": 1229, "en": "once", "ja": "一度", "cat": "副詞" },
    { "id": 1230, "en": "only", "ja": "唯一の", "cat": "形容詞" },
    { "id": 1231, "en": "open", "ja": "開いている", "cat": "形容詞" },
    { "id": 1232, "en": "other", "ja": "他の", "cat": "形容詞" },
    { "id": 1233, "en": "out", "ja": "外へ", "cat": "副詞" },
    { "id": 1234, "en": "outside", "ja": "外側で", "cat": "副詞" },
    { "id": 1235, "en": "own", "ja": "自分自身の", "cat": "形容詞" },
    { "id": 1236, "en": "perfect", "ja": "完全な", "cat": "形容詞" },
    { "id": 1237, "en": "perhaps", "ja": "ことによると", "cat": "副詞" },
    { "id": 1238, "en": "poor", "ja": "貧しい・下手な", "cat": "形容詞" },
    { "id": 1239, "en": "popular", "ja": "人気のある", "cat": "形容詞" },
    { "id": 1240, "en": "possible", "ja": "可能な", "cat": "形容詞" },
    { "id": 1241, "en": "pretty", "ja": "可愛い", "cat": "形容詞" },
    { "id": 1242, "en": "probably", "ja": "おそらく", "cat": "副詞" },
    { "id": 1243, "en": "proud", "ja": "誇りに思う", "cat": "形容詞" },
    { "id": 1244, "en": "quiet", "ja": "静かな", "cat": "形容詞" },
    { "id": 1245, "en": "quite", "ja": "かなり", "cat": "副詞" },
    { "id": 1246, "en": "ready", "ja": "準備ができて", "cat": "形容詞" },
    { "id": 1247, "en": "real", "ja": "本当の", "cat": "形容詞" },
    { "id": 1248, "en": "really", "ja": "本当に", "cat": "副詞" },
    { "id": 1249, "en": "recently", "ja": "最近", "cat": "副詞" },
    { "id": 1250, "en": "rich", "ja": "金持ちの", "cat": "形容詞" },
    { "id": 1251, "en": "right", "ja": "正しい・右の", "cat": "形容詞" },
    { "id": 1252, "en": "sad", "ja": "悲しい", "cat": "形容詞" },
    { "id": 1253, "en": "safe", "ja": "安全な", "cat": "形容詞" },
    { "id": 1254, "en": "same", "ja": "同じ", "cat": "形容詞" },
    { "id": 1255, "en": "serious", "ja": "深刻な", "cat": "形容詞" },
    { "id": 1256, "en": "short", "ja": "短い", "cat": "形容詞" },
    { "id": 1257, "en": "shy", "ja": "内気な", "cat": "形容詞" },
    { "id": 1258, "en": "sick", "ja": "病気の", "cat": "形容詞" },
    { "id": 1259, "en": "simple", "ja": "単純な", "cat": "形容詞" },
    { "id": 1260, "en": "slow", "ja": "遅い", "cat": "形容詞" },
    { "id": 1261, "en": "slowly", "ja": "ゆっくりと", "cat": "副詞" },
    { "id": 1262, "en": "small", "ja": "小さい", "cat": "形容詞" },
    { "id": 1263, "en": "so", "ja": "とても・だから", "cat": "副詞" },
    { "id": 1264, "en": "soft", "ja": "柔らかい", "cat": "形容詞" },
    { "id": 1265, "en": "sometimes", "ja": "時々", "cat": "副詞" },
    { "id": 1266, "en": "soon", "ja": "すぐに", "cat": "副詞" },
    { "id": 1267, "en": "sorry", "ja": "気の毒で", "cat": "形容詞" },
    { "id": 1268, "en": "special", "ja": "特別な", "cat": "形容詞" },
    { "id": 1269, "en": "still", "ja": "まだ", "cat": "副詞" },
    { "id": 1270, "en": "strange", "ja": "奇妙な", "cat": "形容詞" },
    { "id": 1271, "en": "strong", "ja": "強い", "cat": "形容詞" },
    { "id": 1272, "en": "stupid", "ja": "愚かな", "cat": "形容詞" },
    { "id": 1273, "en": "successful", "ja": "成功した", "cat": "形容詞" },
    { "id": 1274, "en": "such", "ja": "そのような", "cat": "形容詞" },
    { "id": 1275, "en": "sudden", "ja": "突然の", "cat": "形容詞" },
    { "id": 1276, "en": "suddenly", "ja": "突然", "cat": "副詞" },
    { "id": 1277, "en": "sunny", "ja": "晴れた", "cat": "形容詞" },
    { "id": 1278, "en": "sure", "ja": "確信して", "cat": "形容詞" },
    { "id": 1279, "en": "sweet", "ja": "甘い", "cat": "形容詞" },
    { "id": 1280, "en": "tall", "ja": "背が高い", "cat": "形容詞" },
    { "id": 1281, "en": "terrible", "ja": "ひどい", "cat": "形容詞" },
    { "id": 1282, "en": "then", "ja": "その時", "cat": "副詞" },
    { "id": 1283, "en": "thirsty", "ja": "喉が渇いた", "cat": "形容詞" },
    { "id": 1284, "en": "tired", "ja": "疲れた", "cat": "形容詞" },
    { "id": 1285, "en": "together", "ja": "一緒に", "cat": "副詞" },
    { "id": 1286, "en": "too", "ja": "〜もまた", "cat": "副詞" },
    { "id": 1287, "en": "traditional", "ja": "伝統的な", "cat": "形容詞" },
    { "id": 1288, "en": "true", "ja": "本当の", "cat": "形容詞" },
    { "id": 1289, "en": "useful", "ja": "役に立つ", "cat": "形容詞" },
    { "id": 1290, "en": "usual", "ja": "いつもの", "cat": "形容詞" },
    { "id": 1291, "en": "usually", "ja": "たいてい", "cat": "副詞" },
    { "id": 1292, "en": "very", "ja": "とても", "cat": "副詞" },
    { "id": 1293, "en": "warm", "ja": "暖かい", "cat": "形容詞" },
    { "id": 1294, "en": "weak", "ja": "弱い", "cat": "形容詞" },
    { "id": 1295, "en": "well", "ja": "上手に", "cat": "副詞" },
    { "id": 1296, "en": "wet", "ja": "濡れた", "cat": "形容詞" },
    { "id": 1297, "en": "white", "ja": "白い", "cat": "形容詞" },
    { "id": 1298, "en": "whole", "ja": "全体の", "cat": "形容詞" },
    { "id": 1299, "en": "wide", "ja": "広い", "cat": "形容詞" },
    { "id": 1300, "en": "wild", "ja": "野生の", "cat": "形容詞" },
    { "id": 1301, "en": "wonderful", "ja": "素晴らしい", "cat": "形容詞" },
    { "id": 1302, "en": "wrong", "ja": "間違った", "cat": "形容詞" },
    { "id": 1303, "en": "yet", "ja": "まだ", "cat": "副詞" },
    { "id": 1304, "en": "young", "ja": "若い", "cat": "形容詞" },
    { "id": 2001, "en": "a few", "ja": "少数の", "cat": "熟語" },
    { "id": 2002, "en": "a little", "ja": "少しの", "cat": "熟語" },
    { "id": 2003, "en": "a lot of", "ja": "たくさんの", "cat": "熟語" },
    { "id": 2004, "en": "after school", "ja": "放課後", "cat": "熟語" },
    { "id": 2005, "en": "agree with", "ja": "～に賛成する", "cat": "熟語" },
    { "id": 2006, "en": "all day", "ja": "一日中", "cat": "熟語" },
    { "id": 2007, "en": "all over", "ja": "至る所に", "cat": "熟語" },
    { "id": 2008, "en": "arrive at", "ja": "～に到着する", "cat": "熟語" },
    { "id": 2009, "en": "ask for", "ja": "～を求める", "cat": "熟語" },
    { "id": 2010, "en": "at first", "ja": "最初は", "cat": "熟語" },
    { "id": 2011, "en": "at home", "ja": "在宅して", "cat": "熟語" },
    { "id": 2012, "en": "at last", "ja": "ついに", "cat": "熟語" },
    { "id": 2013, "en": "at once", "ja": "すぐに", "cat": "熟語" },
    { "id": 2014, "en": "at that time", "ja": "その時", "cat": "熟語" },
    { "id": 2015, "en": "be able to", "ja": "～できる", "cat": "熟語" },
    { "id": 2016, "en": "be absent from", "ja": "～を欠席する", "cat": "熟語" },
    { "id": 2017, "en": "be born", "ja": "生まれる", "cat": "熟語" },
    { "id": 2018, "en": "be covered with", "ja": "～で覆われる", "cat": "熟語" },
    { "id": 2019, "en": "be different from", "ja": "～と異なる", "cat": "熟語" },
    { "id": 2020, "en": "be famous for", "ja": "～で有名だ", "cat": "熟語" },
    { "id": 2021, "en": "be full of", "ja": "～で一杯だ", "cat": "熟語" },
    { "id": 2022, "en": "be glad to", "ja": "～して嬉しい", "cat": "熟語" },
    { "id": 2023, "en": "be good at", "ja": "～が得意だ", "cat": "熟語" },
    { "id": 2024, "en": "be interested in", "ja": "～に興味がある", "cat": "熟語" },
    { "id": 2025, "en": "be late for", "ja": "～に遅れる", "cat": "熟語" },
    { "id": 2026, "en": "be made of", "ja": "～で作られる", "cat": "熟語" },
    { "id": 2027, "en": "be proud of", "ja": "～を誇る", "cat": "熟語" },
    { "id": 2028, "en": "be ready for", "ja": "～の準備ができている", "cat": "熟語" },
    { "id": 2029, "en": "be surprised at", "ja": "～に驚く", "cat": "熟語" },
    { "id": 2030, "en": "belong to", "ja": "～に所属する", "cat": "熟語" },
    { "id": 2031, "en": "between A and B", "ja": "AとBの間に", "cat": "熟語" },
    { "id": 2032, "en": "both A and B", "ja": "AもBも両方", "cat": "熟語" },
    { "id": 2033, "en": "by the way", "ja": "ところで", "cat": "熟語" },
    { "id": 2034, "en": "care about", "ja": "～を気にする", "cat": "熟語" },
    { "id": 2035, "en": "catch cold", "ja": "風邪をひく", "cat": "熟語" },
    { "id": 2036, "en": "come back", "ja": "戻ってくる", "cat": "熟語" },
    { "id": 2037, "en": "come from", "ja": "～出身である", "cat": "熟語" },
    { "id": 2038, "en": "come home", "ja": "帰宅する", "cat": "熟語" },
    { "id": 2039, "en": "come in", "ja": "入る", "cat": "熟語" },
    { "id": 2040, "en": "come true", "ja": "実現する", "cat": "熟語" },
    { "id": 2041, "en": "decide to", "ja": "～を決心する", "cat": "熟語" },
    { "id": 2042, "en": "do one's best", "ja": "最善を尽くす", "cat": "熟語" },
    { "id": 2043, "en": "each other", "ja": "お互いに", "cat": "熟語" },
    { "id": 2044, "en": "enjoy ing", "ja": "～して楽しむ", "cat": "熟語" },
    { "id": 2045, "en": "fall down", "ja": "倒れる", "cat": "熟語" },
    { "id": 2046, "en": "far away", "ja": "遠く離れて", "cat": "熟語" },
    { "id": 2047, "en": "find out", "ja": "見つけ出す", "cat": "熟語" },
    { "id": 2048, "en": "finish ing", "ja": "～し終える", "cat": "熟語" },
    { "id": 2049, "en": "for a long time", "ja": "長い間", "cat": "熟語" },
    { "id": 2050, "en": "for example", "ja": "例えば", "cat": "熟語" },
    { "id": 2051, "en": "for the first time", "ja": "初めて", "cat": "熟語" },
    { "id": 2052, "en": "get off", "ja": "（乗り物を）降りる", "cat": "熟語" },
    { "id": 2053, "en": "get on", "ja": "（乗り物に）乗る", "cat": "熟語" },
    { "id": 2054, "en": "get to", "ja": "～に着く", "cat": "熟語" },
    { "id": 2055, "en": "get up", "ja": "起きる", "cat": "熟語" },
    { "id": 2056, "en": "get well", "ja": "良くなる", "cat": "熟語" },
    { "id": 2057, "en": "give up", "ja": "あきらめる", "cat": "熟語" },
    { "id": 2058, "en": "go out", "ja": "外出する", "cat": "熟語" },
    { "id": 2059, "en": "go shopping", "ja": "買い物に行く", "cat": "熟語" },
    { "id": 2060, "en": "go to bed", "ja": "寝る", "cat": "熟語" },
    { "id": 2061, "en": "grow up", "ja": "成長する", "cat": "熟語" },
    { "id": 2062, "en": "have a good time", "ja": "楽しむ", "cat": "熟語" },
    { "id": 2063, "en": "have to", "ja": "～しなければならない", "cat": "熟語" },
    { "id": 2064, "en": "hear from", "ja": "～から便りがある", "cat": "熟語" },
    { "id": 2065, "en": "help A with B", "ja": "AのBを手伝う", "cat": "熟語" },
    { "id": 2066, "en": "How about", "ja": "～はどうですか", "cat": "熟語" },
    { "id": 2067, "en": "hundreds of", "ja": "何百もの", "cat": "熟語" },
    { "id": 2068, "en": "in front of", "ja": "～の前に", "cat": "熟語" },
    { "id": 2069, "en": "in the future", "ja": "将来", "cat": "熟語" },
    { "id": 2070, "en": "invite A to B", "ja": "AをBに招待する", "cat": "熟語" },
    { "id": 2071, "en": "kind of", "ja": "種類", "cat": "熟語" },
    { "id": 2072, "en": "listen to", "ja": "～を聞く", "cat": "熟語" },
    { "id": 2073, "en": "look after", "ja": "世話をする", "cat": "熟語" },
    { "id": 2074, "en": "look at", "ja": "～を見る", "cat": "熟語" },
    { "id": 2075, "en": "look for", "ja": "～を探す", "cat": "熟語" },
    { "id": 2076, "en": "look forward to", "ja": "～を楽しみにする", "cat": "熟語" },
    { "id": 2077, "en": "look like", "ja": "～のように見える", "cat": "熟語" },
    { "id": 2078, "en": "make friends with", "ja": "～と友達になる", "cat": "熟語" },
    { "id": 2079, "en": "more than", "ja": "～以上", "cat": "熟語" },
    { "id": 2080, "en": "next to", "ja": "～の隣に", "cat": "熟語" },
    { "id": 2081, "en": "not only A but also B", "ja": "AだけでなくBも", "cat": "熟語" },
    { "id": 2082, "en": "of course", "ja": "もちろん", "cat": "熟語" },
    { "id": 2083, "en": "one day", "ja": "ある日", "cat": "熟語" },
    { "id": 2084, "en": "over there", "ja": "あそこに", "cat": "熟語" },
    { "id": 2085, "en": "part of", "ja": "～の一部", "cat": "熟語" },
    { "id": 2086, "en": "plenty of", "ja": "たくさんの", "cat": "熟語" },
    { "id": 2087, "en": "put on", "ja": "着る", "cat": "熟語" },
    { "id": 2088, "en": "right now", "ja": "今すぐ", "cat": "熟語" },
    { "id": 2089, "en": "run away", "ja": "逃げる", "cat": "熟語" },
    { "id": 2090, "en": "shake hands", "ja": "握手する", "cat": "熟語" },
    { "id": 2091, "en": "show A around B", "ja": "AにBを案内する", "cat": "熟語" },
    { "id": 2092, "en": "some day", "ja": "いつか", "cat": "熟語" },
    { "id": 2093, "en": "speak to", "ja": "～に話しかける", "cat": "熟語" },
    { "id": 2094, "en": "stand up", "ja": "立ち上がる", "cat": "熟語" },
    { "id": 2095, "en": "stop ing", "ja": "～するのをやめる", "cat": "熟語" },
    { "id": 2096, "en": "take a picture", "ja": "写真を撮る", "cat": "熟語" },
    { "id": 2097, "en": "take care of", "ja": "世話をする", "cat": "熟語" },
    { "id": 2098, "en": "take part in", "ja": "～に参加する", "cat": "熟語" },
    { "id": 2099, "en": "talk about", "ja": "～について話す", "cat": "熟語" },
    { "id": 2100, "en": "talk to", "ja": "～と話す", "cat": "熟語" },
    { "id": 2101, "en": "thank you for", "ja": "～をありがとう", "cat": "熟語" },
    { "id": 2102, "en": "try to", "ja": "～しようとする", "cat": "熟語" },
    { "id": 2103, "en": "turn off", "ja": "消す", "cat": "熟語" },
    { "id": 2104, "en": "turn on", "ja": "つける", "cat": "熟語" },
    { "id": 2105, "en": "wait for", "ja": "～を待つ", "cat": "熟語" },
    { "id": 2106, "en": "wake up", "ja": "目が覚める", "cat": "熟語" },
    { "id": 2107, "en": "want to", "ja": "～したい", "cat": "熟語" },
    { "id": 2108, "en": "work hard", "ja": "一生懸命働く", "cat": "熟語" },
    { "id": 2109, "en": "would like to", "ja": "～したい", "cat": "熟語" },
    { "id": 2110, "en": "write to", "ja": "～に手紙を書く", "cat": "熟語" },



    



    
];
